# Pre-requisites

In [3]:
#********************** to be run only once ************************************
#pip install -U sentence-transformers
#pip install --user annoy
#export CC=/usr/bin/clang ; export CXX=/usr/bin/clang++

# Code Starts

In [304]:
import edaSQL
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt
import time

In [ ]:
#DB connection
edasql = edaSQL.SQL()
edasql.connectToDataBase(server='', #Info removed to comply with the NDA
                         database='', #Info removed to comply with the NDA
                         user='', #Info removed to comply with the NDA
                         password='',#Info removed to comply with the NDA
                         sqlDriver='ODBC Driver 17 for SQL Server')

In [ ]:
start = time.time()

# Getting Type1s data:
ctrQuery = "select * from <> ctr" #Info removed to comply with the NDA
ctrData = pd.read_sql(ctrQuery, edasql.dbConnection)

end = time.time()

# Total time to compute
print('\nThis function took {:.2f} s to compute.'.format(end - start))

In [ ]:
ctrData

In [129]:
#Missing values
ctrData['Type1ingProcedureType'] = ctrData['Type1ingProcedureType'].replace('', 'No Info')
ctrData['Type1ingProcedureType'][13833]

ctrData['Type1Type'] = ctrData['Type1Type'].replace('', 'No Info')
ctrData['Type1Type'][13833]

'No Info'

In [ ]:
#set seaborn plotting aesthetics
sns.set(rc = {'figure.figsize':(30,20)})

#Plot
plot1 = sns.countplot(data=ctrData, x="Type1ingProcedureType")
plot1.bar_label(plot1.containers[0], size=20)
plt.title('Type1s - Type1ing Procedure Type', fontsize=35)
plt.xticks(fontsize=20, rotation ='vertical')
plt.yticks(fontsize=20)
plt.xlabel('Type1ing Procedure Type', fontsize=25)
plt.ylabel('Type1s Count', fontsize=25)

#Cleared Output to comply with the NDA

In [131]:

import time
start = time.time()

# Getting Type1s data: parsedPriceBracket, executionDeadlineDays
ctrQuery_1 = "select * " #Info removed to comply with the NDA
ctrData_1 = pd.read_sql(ctrQuery_1, edasql.dbConnection)

end = time.time()

# Total time to compute
print('\nThis function took {:.2f} s to compute.'.format(end - start))

This function took 2.46 s to compute.

# parsedPriceBracket 
#   0 --'<0' 
#   1 --'0-100000' 
#	2 --'100001-500000' 
#	3 --'500001-1000000' 
#	4 --'1000001-3000000' 
#	5 --'3000001-9000000' 
#	6 --'9000000-20000000' 
#	7 --'20000001-50000000' 
#	8 --'50000001-100000000' 
#	9 --'100000001-200000000' 
#	10 --'200000001-400000000' 
#	11 --'400000001-1000000000' 
#	12 --'>1000000000'

# executionDeadlineDays (Brackets)
#   1 --'0-15' 
#   2 --'15-30' 
#   3 --'31-45' 
#   4 --'46-60' 
#   5 --'61-90' 
#   6 --'91-120' 
#   7 --'121-150' 
#   8 --'151-180' 
#   9 --'181-270' 
#   10 --'271-365' 
#   11 --'366-730' 
#   12 --'731-1095' 
#   13 --'1096-1460' 
#   14 --'1461-1825' 
#   15 --'>1825'

In [ ]:
ctrData_1

In [132]:

import time
start = time.time()

# Merge Type1s data: with parsedPriceBracket, executionDeadlineDays
Data_ctr = []
Data_ctr = ctrData.merge(ctrData_1, how='left', on='id')

end = time.time()

# Total time to compute
print('\nThis function took {:.2f} s to compute.'.format(end - start))

This function took 1.35 s to compute.

In [ ]:
Data_ctr

In [ ]:
#set seaborn plotting aesthetics as default
sns.set()

#define plotting region (2 rows, 2 columns)
fig, axs = plt.subplots(1, 2)

#Plot
plot2 = sns.histplot(data=Data_ctr, x="parsedPriceBracket", ax=axs[0])
plot2.axes.set_title("Type1s - Parsed Price",fontsize=50)
plot2.set_xlabel("Parsed Price Bracket",fontsize=30)
plot2.set_ylabel("Type1s Count",fontsize=20)
plot2.bar_label(plot2.containers[0], size=20)
plot2.tick_params(labelsize=20)

plot3 = sns.histplot(data=Data_ctr, x="executionDeadlineDays", ax=axs[1])
plot3.axes.set_title("Type1s - Execution DeadLine",fontsize=50)
plot3.bar_label(plot3.containers[0], size=20)
plot3.set_xlabel("Execution Deadline Days",fontsize=30)
plot3.set_ylabel("Type1s Count",fontsize=20)
plot3.bar_label(plot3.containers[0], size=20)
plot3.tick_params(labelsize=20)

#Cleared Output to comply with the NDA

In [15]:
Data_ctr.isnull().sum()

lemm                           0
ctr_ads                        0
id                             0
contractingProcedureType       0
contractType                   0
objectBriefDescription         0
contractingCount               0
country_orig                9878
parsedPriceBracket             0
executionDeadlineDays          0
dtype: int64

In [141]:
import time
start = time.time()

# Getting Type1s data: category1sSplit
ctrQuery_2 = "select * from <>. ctr cross apply string_split(ctr.category1s,'|')) abc cross apply string_split(abc.category1s,'>')" #Info removed to comply with the NDA
ctrData_2 = pd.read_sql(ctrQuery_2, edasql.dbConnection)

end = time.time()

# Total time to compute
print('\nThis function took {:.2f} s to compute.'.format(end - start))

This function took 2.77 s to compute.

In [ ]:
ctrData_2

In [143]:

import time
start = time.time()

# Merge Type1s data: with category1sSplit
Data_ctr = Data_ctr.merge(ctrData_2, how='inner', on='id')

end = time.time()

# Total time to compute
print('\nThis function took {:.2f} s to compute.'.format(end - start))

This function took 2.11 s to compute.

In [19]:
Data_ctr.isnull().sum()

lemm                            0
ctr_ads                         0
id                              0
contractingProcedureType        0
contractType                    0
objectBriefDescription          0
contractingCount                0
country_orig                10135
parsedPriceBracket              0
executionDeadlineDays           0
cpvsSplit                       0
dtype: int64

In [ ]:
Data_ctr

In [ ]:
#Plot
sns.scatterplot(data=Data_ctr, x="Type1ingProcedureType", y="parsedPriceBracket", size="id", sizes=(40, 400))
plt.title('Type1s distribution', fontsize=35)
plt.xticks(fontsize=20, rotation ='vertical')
plt.yticks(fontsize=20)
plt.xlabel('Type1ing Procedure Type', fontsize=25)
plt.ylabel('Parsed price Bracket', fontsize=25)

#Cleared Output to comply with the NDA

In [ ]:
#Plot
df2 = pd.concat([Data_ctr['Type1ingProcedureType'],Data_ctr['category1sSplit']], axis=1)
df2 = df2.drop_duplicates()

sns.set(rc = {'figure.figsize':(30,20)})
plot1 = sns.countplot(data=df2, x="Type1ingProcedureType")
plot1.bar_label(plot1.containers[0], size=20)
plt.title('Distinct category1sSplit count per Type1ing Procedure Type', fontsize=35)
plt.xticks(fontsize=20, rotation ='vertical')
plt.yticks(fontsize=20)
plt.xlabel('Type1ing Procedure Type', fontsize=25)
plt.ylabel('Distinct category1sSplit Count', fontsize=25)

#Cleared Output to comply with the NDA

In [144]:
start = time.time()

# Getting Type1s data: nif
ctrQuery_nif = "select * from  <> ctr union select * from <> nif" #Info removed to comply with the NDA
ctrData_nif = pd.read_sql(ctrQuery_nif, edasql.dbConnection)

end = time.time()

# Total time to compute
print('\nThis function took {:.2f} s to compute.'.format(end - start))

This function took 2.70 s to compute.

In [ ]:
ctrData_nif

In [146]:
import time
start = time.time()

# Merge Type1s data: with nif
Data_ctr = Data_ctr.merge(ctrData_nif, how='left', on='id')

end = time.time()

# Total time to compute
print('\nThis function took {:.2f} s to compute.'.format(end - start))

This function took 1.04 s to compute.

In [ ]:
Data_ctr

In [ ]:
df3 = Data_ctr[["Type1ingProcedureType","nif"]]
df3 = df3.drop_duplicates()

#Plot
sns.set(rc = {'figure.figsize':(30,20)})
plot1 = sns.countplot(data=df3, x="Type1ingProcedureType")
plot1.bar_label(plot1.containers[0], size=20)
plt.title('Distinct Buyers per Type1ing Procedure Type', fontsize=35)
plt.xticks(fontsize=20, rotation ='vertical')
plt.yticks(fontsize=20)
plt.xlabel('Type1ing Procedure Type', fontsize=25)
plt.ylabel('Distinct Buyers', fontsize=25)

#Cleared Output to comply with the NDA

In [ ]:
df4 = Data_ctr[["id", "parsedPriceBracket","executionDeadlineDays"]].reset_index(drop=True)
df4 = df4.drop_duplicates().reset_index(drop=True)
df4 = df4.pivot_table(index='executionDeadlineDays', columns='parsedPriceBracket', values='id', aggfunc='count')

#Plot
ax = sns.heatmap(df4,cmap="PiYG", annot=True, fmt=".0f", annot_kws={"fontsize":20})
cbar = ax.collections[0].colorbar
cbar.ax.tick_params(labelsize=20)
plt.title('Type1s Data', fontsize=35)
plt.xticks(fontsize=20)
plt.yticks(fontsize=20, rotation ='vertical')
plt.xlabel('Execution Deadline Days Bracket', fontsize=25)
plt.ylabel('Parsed Price Bracket', fontsize=25)
plt.show()

#Cleared Output to comply with the NDA

# Fetching Data from the Db : Type2s

In [147]:
start = time.time()

# Getting Type2s data:
Type2sQuery = "select * from <> Type2s" #Info removed to comply with the NDA
Type2sData = pd.read_sql(Type2sQuery, edasql.dbConnection)

end = time.time()

# Total time to compute
print('\nThis function took {:.2f} s to compute.'.format(end - start))

This function took 7.44 s to compute.

In [ ]:
Type2sData

In [148]:
start = time.time()

# Getting Type2s data: parsedPriceBracket, executionDeadlineDays
Type2sQuery_1 = "select * from <> Type2s" #Info removed to comply with the NDA
Type2sData_1 = pd.read_sql(Type2sQuery_1, edasql.dbConnection)

end = time.time()

# Total time to compute
print('\nThis function took {:.2f} s to compute.'.format(end - start))

This function took 0.69 s to compute.

In [ ]:
Type2sData_1

In [153]:

import time
start = time.time()

# Merge Type2s data: with parsedPriceBracket, executionDeadlineDays
Data_Type2s = []
Data_Type2s = Type2sData.merge(Type2sData_1, how='left', on='id')

end = time.time()

# Total time to compute
print('\nThis function took {:.2f} s to compute.'.format(end - start))

This function took 0.22 s to compute.

In [ ]:
Data_Type2s

In [155]:
start = time.time()

# Getting Type2s data: Category1Split
Type2sQuery_2 = "select * from <> Type2s cross apply string_split(Type2s.Category1,'|')) abc cross apply string_split(abc.Category1,'>')" #Info removed to comply with the NDA
Type2sData_2 = pd.read_sql(Type2sQuery_2, edasql.dbConnection)

end = time.time()

# Total time to compute
print('\nThis function took {:.2f} s to compute.'.format(end - start))

This function took 0.64 s to compute.

In [ ]:
Type2sData_2

In [157]:

import time
start = time.time()

# Merge Type2s data: with category1sSplit
Data_Type2s = Data_Type2s.merge(Type2sData_2, how='inner', on='id')

end = time.time()

# Total time to compute
print('\nThis function took {:.2f} s to compute.'.format(end - start))

This function took 0.09 s to compute.

In [ ]:
Data_Type2s

In [159]:
start = time.time()

# Getting Type2s data: nif
Type2sQuery_nif = "select * from <> Type2s" #Info removed to comply with the NDA
Type2sData_nif = pd.read_sql(Type2sQuery_nif, edasql.dbConnection)

end = time.time()

# Total time to compute
print('\nThis function took {:.2f} s to compute.'.format(end - start))

This function took 0.75 s to compute.

In [ ]:
Type2sData_nif

In [ ]:
Type2sData_nif.drop_duplicates()

In [160]:

import time
start = time.time()

# Merge Type2s data: with nif
Data_Type2s = Data_Type2s.merge(Type2sData_nif, how='left', on='id')

end = time.time()

# Total time to compute
print('\nThis function took {:.2f} s to compute.'.format(end - start))

This function took 0.11 s to compute.

In [ ]:
Data_Type2s

In [ ]:
#set seaborn plotting aesthetics as default
sns.set()

#define plotting region (2 rows, 2 columns)
fig, axs = plt.subplots(1, 2)

#Plot
plot2 = sns.countplot(data=Data_Type2s, x="parsedPriceBracket", ax=axs[0])
plot2.axes.set_title("Type2s - Parsed Price",fontsize=50)
plot2.set_xlabel("Parced Price Bracket",fontsize=30)
plot2.set_ylabel("Type2s Count",fontsize=20)
plot2.bar_label(plot2.containers[0], size=20)
plot2.tick_params(labelsize=20)

df5 = Data_Type2s[["parsedPriceBracket","nif"]].reset_index(drop=True)
df5 = df5.drop_duplicates().reset_index(drop=True)

#Plot
plot3 = sns.countplot(data=df5, x="parsedPriceBracket", ax=axs[1])
plot3.axes.set_title("Buyers - Parsed Price",fontsize=50)
plot3.bar_label(plot3.containers[0], size=20)
plot3.set_xlabel("Parced Price Bracket",fontsize=30)
plot3.set_ylabel("Distinct Buyers Count",fontsize=20)
plot3.bar_label(plot3.containers[0], size=20)
plot3.tick_params(labelsize=20)

#Cleared Output to comply with the NDA

In [161]:
#Combine Type1s and Type2s into single df for Location info merging
fullData =  pd.concat([Data_ctr, Data_Type2s], ignore_index=True)

In [ ]:
fullData

In [ ]:
fullData.isnull().sum()

In [ ]:
fullData[ (fullData.ctr_Type2s =='Type2s') & (fullData.nif.isnull())]

In [162]:
start = time.time()

# Getting data: loc
Query_loc = "select * " #Info removed to comply with the NDA
Data_loc = pd.read_sql(Query_loc, edasql.dbConnection)

end = time.time()

# Total time to compute
print('\nThis function took {:.2f} s to compute.'.format(end - start))

This function took 0.76 s to compute.

In [ ]:
Data_loc

In [163]:

import time
start = time.time()

# Merge loc data:
Full_Data = fullData.merge(Data_loc, how='left', on='nif')

end = time.time()

# Total time to compute
print('\nThis function took {:.2f} s to compute.'.format(end - start))

This function took 1.02 s to compute.

In [164]:
Full_Data['country_nif'] = Full_Data['country_nif'].str.capitalize()

In [ ]:
Full_Data

In [ ]:
Full_Data[((Full_Data.country_orig =='NA') | (Full_Data.country_orig ==None))]

In [ ]:
Full_Data.isnull().sum()

In [166]:
import numpy as np
#Full_Data.drop(['country'], axis = 1)
#Full_Data["country"] = Full_Data['country_orig'].apply(lambda x: x if x!='NA' )
Full_Data['country'] = np.where((Full_Data['country_orig'] == 'NA'), Full_Data['country_nif'], Full_Data['country_orig'])
Full_Data['country'] = np.where((Full_Data['country'] == None), Full_Data['country_nif'], Full_Data['country'])

In [167]:
start = time.time()

# Getting Geo data
Query_geo = "select *" #Info removed to comply with the NDA
Data_geo = pd.read_sql(Query_geo, edasql.dbConnection)

end = time.time()

# Total time to compute
print('\nThis function took {:.2f} s to compute.'.format(end - start))

This function took 0.10 s to compute.

In [168]:

import time
start = time.time()

# Merge Geo data:
Full_Data = Full_Data.merge(Data_geo, how='left', on='county')

end = time.time()

# Total time to compute
print('\nThis function took {:.2f} s to compute.'.format(end - start))

This function took 0.81 s to compute.

In [169]:
Full_Data["country_geo"].fillna("No Info", inplace = True)
Full_Data["country_orig"].fillna("No Info", inplace = True)
Full_Data.country_orig[Full_Data['country_orig'].str.contains('Portugal')] = 'Portugal'
Full_Data.country_orig[(Full_Data['country_orig'].str.contains('<BR/>'))& (Full_Data['country_geo']!= 'Portugal')] = 'Multiple'
Full_Data.country_orig[(Full_Data['country_orig'].str.contains('<BR/>'))& (Full_Data['country_geo']== 'Portugal')] = 'Portugal'
Full_Data.country_orig[Full_Data['country_orig'] == ''] = 'No Info'
Full_Data.country_orig[Full_Data['country_orig'] == 'NA'] = 'No Info'

In [ ]:
Full_Data

In [ ]:

#Plot
sns.set(rc = {'figure.figsize':(30,20)})
plot1 = sns.countplot(data=Full_Data, x="ctr_Type2s")
plot1.bar_label(plot1.containers[0], size=20)
plt.title('Type1s and Type2s per Country of Origin', fontsize=35)
plt.xticks(fontsize=20, rotation ='vertical')
plt.yticks(fontsize=20)
plt.xlabel('Type1s and Type2s', fontsize=25)
plt.ylabel('Count', fontsize=25)
#plt.legend(loc='upper right')

#Cleared Output to comply with the NDA

In [171]:
data_df = Full_Data.drop(columns = ['country', 'country_nif', 'country_geo', 'Type1ingCount'])
data_df.rename(columns = {'country_orig':'country'}, inplace = True)

# Ordinal Encoding for Categorical Features

In [172]:
data_df["ctr_Type2s"] = data_df["ctr_Type2s"].astype('category')
data_df["Type1ingProcedureType"] = data_df["Type1ingProcedureType"].astype('category')
data_df["Type1Type"] = data_df["Type1Type"].astype('category')
data_df["parsedPriceBracket"] = data_df["parsedPriceBracket"].astype('category')
data_df["executionDeadlineDays"] = data_df["executionDeadlineDays"].astype('category')
#data_df["category1sSplit"] = data_df["category1sSplit"].astype('category')
data_df["nif"] = data_df["nif"].astype('category')
data_df["county"] = data_df["county"].astype('category')
data_df["country"] = data_df["country"].astype('category')

In [173]:
data_df["ctr_Type2s"] = data_df["ctr_Type2s"].cat.codes
#data_df["Type1ingProcedureType"] = data_df["Type1ingProcedureType"].cat.codes
#data_df["Type1Type"] = data_df["Type1Type"].cat.codes
data_df["parsedPriceBracket"] = data_df["parsedPriceBracket"].cat.codes
data_df["executionDeadlineDays"] = data_df["executionDeadlineDays"].cat.codes
#data_df["category1sSplit"] = data_df["category1sSplit"].cat.codes
data_df["nif"] = data_df["nif"].cat.codes
data_df["county"] = data_df["county"].cat.codes
data_df["country"] = data_df["country"].cat.codes

In [ ]:
data_df.info()

In [174]:
data_df.select_dtypes(include=['object','category']).columns.tolist()

['lemm',
 'contractingProcedureType',
 'contractType',
 'objectBriefDescription',
 'cpvsSplit']

In [175]:
data_df = data_df.drop_duplicates()

# Trying category1s text

In [ ]:
import time
start = time.time()

# Getting Type1s data: category1sSplit and text
ctr_category1s_query = "select * from <> ctr cross apply string_split(ctr.category1s,'|')) abc cross apply string_split(abc.category1s,'>')) def where category1s_text is NOT NULL" #Info removed to comply with the NDA
ctr_category1s_data = pd.read_sql(ctr_category1s_query, edasql.dbConnection)

end = time.time()

# Total time to compute
print('\nThis function took {:.2f} s to compute.'.format(end - start))

In [180]:

import time
start = time.time()

# Merge category1S Text data:
data_df_new = data_df.merge(ctr_category1s_data, how='left', on='category1sSplit')

end = time.time()

# Total time to compute
print('\nThis function took {:.2f} s to compute.'.format(end - start))

This function took 0.72 s to compute.

In [ ]:
data_df_new

# Sampling for Faster Processing

#Using Subset of the data due to dataset being huge while processing capacity on my laptop is limited.
#This same code can be deployed using scalable power for the whole dataset.

In [ ]:
#using Type1 nos from the test set
ctr_list = [] #Info removed to comply with the NDA

#plus 10K Type1s
samp_ctr = data_df_new[(data_df_new.ctr_Type2s == 1) & (data_df_new.category1s_text != None)].head(10000)
samp_ctr = samp_ctr.append(data_df_new[data_df_new['id'].isin(ctr_list)]).reset_index(drop=True) 
samp_ctr

In [ ]:
#using Type2s nos from the test set
Type2s_list = [] #Info removed to comply with the NDA

#plus 10K Type2s
samp_Type2s = data_df[(data_df.ctr_Type2s == 0)].head(10000)
samp_Type2s = samp_Type2s.append(data_df[data_df['id'].isin(Type2s_list)]).reset_index(drop=True) 
samp_Type2s

In [70]:
#Saving the data
samp_ctr.to_csv("./samp_ctr.csv")
samp_Type2s.to_csv("./samp_Type2s.csv")

# Text Embedding Using all-MiniLM-L6-v2

# Type1s

In [823]:
#Text Embedding for Type1 Titles

from sentence_transformers import SentenceTransformer
model = SentenceTransformer('all-MiniLM-L6-v2')

start = time.time()
embeddings_ctr_1 = []

n = len(samp_ctr['lemm'])

print(f"There are {n} records to process today")
embeddings_ctr_1 = model.encode(samp_ctr['lemm'])
print(f"{n} records are added")

end = time.time()
# Total time to compute

print('\nThis function took {:.2f} s to compute.'.format(end - start))

There are 10203 records to process today
10203 records are added

This function took 148.96 s to compute.

In [ ]:
ctr_embeds_df_1 = pd.DataFrame(embeddings_ctr_1)
ctr_embeds_df_1.columns = ['col_'+str(num) for num in range(embeddings_ctr_1.shape[1])]
ctr_embeds_df_1

In [951]:
#Text Embedding for Ad Titles

from sentence_transformers import SentenceTransformer
model = SentenceTransformer('all-MiniLM-L6-v2')

start = time.time()
embeddings_Type2s_1 = []

n = len(samp_Type2s['lemm'])

print(f"There are {n} records to process today")
embeddings_Type2s_1 = model.encode(samp_Type2s['lemm'])
print(f"{n} records are added")

end = time.time()
# Total time to compute

print('\nThis function took {:.2f} s to compute.'.format(end - start))

There are 10224 records to process today
10224 records are added

This function took 169.62 s to compute.

In [ ]:
Type2s_embeds_df_1 = pd.DataFrame(embeddings_Type2s_1)
Type2s_embeds_df_1.columns = ['col_'+str(num) for num in range(embeddings_Type2s_1.shape[1])]
Type2s_embeds_df_1

# Build the ANNOY index Using all-MiniLM-L6-v2

In [956]:
#Using ANNOY: Approximate Nearest Neighbours Oh yeah! by Spotify for Type1s
from annoy import AnnoyIndex

import time
start = time.time()

f = 384

t_ctr_txt_1 = AnnoyIndex(f, 'angular')  #Length of item vector that will be indexed
#for index, row in dummy_df.head(1000):
   # t.add_item(index, row)
#adf = final_df.iloc[:500000, :]
for index, row in ctr_embeds_df_1.iterrows():
    #print(f"index: {index}, row: {row.nif}")
    t_ctr_txt_1.add_item(index, row)

t_ctr_txt_1.build(10) # 10 trees
t_ctr_txt_1.save('test_ctr_txt_1.ann')

end = time.time()

# Total time to compute
print('\nThis function took {:.2f} s to compute.'.format(end - start))

This function took 12.17 s to compute.

In [957]:
#Using ANNOY: Approximate Nearest Neighbours Oh yeah! by Spotify for Type2s
from annoy import AnnoyIndex

import time
start = time.time()

f = 384

t_Type2s_txt_1 = AnnoyIndex(f, 'angular')  #Length of item vector that will be indexed
#for index, row in dummy_df.head(1000):
   # t.add_item(index, row)
#adf = final_df.iloc[:500000, :]
for index, row in Type2s_embeds_df_1.iterrows():
    #print(f"index: {index}, row: {row.nif}")
    t_Type2s_txt_1.add_item(index, row)

t_Type2s_txt_1.build(10) # 10 trees
t_Type2s_txt_1.save('test_Type2s_txt_1.ann')

end = time.time()

# Total time to compute
print('\nThis function took {:.2f} s to compute.'.format(end - start))

This function took 13.50 s to compute.

# Testing the embeddings Using all-MiniLM-L6-v2

# Type1s

In [ ]:
#TC1
c_no = <> #Info removed to comply with the NDA
c_list = [<>] #Info removed to comply with the NDA


indx = samp_ctr.index[samp_ctr['id'] == c_no].tolist()
print(f"Type1 No.: {c_no} index: {indx}")
print("\nIndexes of Type1s to be matched: ")
print(samp_ctr[samp_ctr['id'].isin(c_list)]['id'])
lst = samp_ctr[samp_ctr['id'].isin(c_list)].index

u = AnnoyIndex(f, 'angular')
u.load('test_ctr_txt_1.ann') # super fast, will just mmap the file
result = pd.DataFrame()
result['Col1'] = pd.DataFrame(u.get_nns_by_item(indx[0], 1000 )) # will find the 1000 nearest neighbors
print("\nMatch Results")
res = result[result['Col1'].isin(lst)].Col1
print(f"{len(res)} records match")
res

#Cleared Output to comply with the NDA

In [ ]:
#TC1
#To view the full list of result
u = AnnoyIndex(f, 'angular')
u.load('test_ctr_txt_1.ann') # super fast, will just mmap the file
result = pd.DataFrame()
result = u.get_nns_by_item(<>, 10 ) # will find the 1000 nearest neighbors #Info removed to comply with the NDA

#result.sort()
print(result)

#Cleared Output to comply with the NDA

In [ ]:
#TC1
samp_ctr[samp_ctr.index.isin([<>])][['id','lemm', 'objectBriefDescription']]#Info removed to comply with the NDA

#Cleared Output to comply with the NDA

# Type2s

In [ ]:
#TC1
a_no = <> #Info removed to comply with the NDA
a_list = [<>] #Info removed to comply with the NDA
indx = samp_Type2s.index[samp_Type2s['id'] == a_no].tolist()
print(f"Ad No.: {a_no} index: {indx}")
print("\nIndexes of Type2s to be matched: ")
print(samp_Type2s[samp_Type2s['id'].isin(a_list)]['id'])
lst = samp_Type2s[samp_Type2s['id'].isin(a_list)].index

u = AnnoyIndex(f, 'angular')
u.load('test_Type2s_txt_1.ann') # super fast, will just mmap the file
result = pd.DataFrame()
result['Col1'] = pd.DataFrame(u.get_nns_by_item(indx[0], 500 )) # will find the 1000 nearest neighbors
print("\nMatch Results")
res = result[result['Col1'].isin(lst)].Col1
print(f"{len(res)} records match")
res

#Cleared Output to comply with the NDA

In [ ]:
#TC2
a_no = <> #Info removed to comply with the NDA
a_list = [<>] #Info removed to comply with the NDA
indx = samp_Type2s.index[samp_Type2s['id'] == a_no].tolist()
print(f"Ad No.: {a_no} index: {indx}")
print("\nIndexes of Type2s to be matched: ")
print(samp_Type2s[samp_Type2s['id'].isin(a_list)]['id'])
lst = samp_Type2s[samp_Type2s['id'].isin(a_list)].index

u = AnnoyIndex(f, 'angular')
u.load('test_Type2s_txt_1.ann') # super fast, will just mmap the file
result = pd.DataFrame()
result['Col1'] = pd.DataFrame(u.get_nns_by_item(indx[0], 500 )) # will find the 1000 nearest neighbors
print("\nMatch Results")
res = result[result['Col1'].isin(lst)].Col1
print(f"{len(res)} records match")
res

#Cleared Output to comply with the NDA

# Removing Numerals and Special Characters from the lemmetised text

In [311]:
#samp_ctr['lemm'] = samp_ctr['lemm'].str.replace('pc\d+', '', regex=True)
#samp_ctr['lemm'] = samp_ctr['lemm'].str.replace('pc-\d+', '', regex=True)
#samp_ctr['lemm'] = samp_ctr['lemm'].str.replace('pc \d+', '', regex=True)
#samp_ctr['lemm'] = samp_ctr['lemm'].str.replace('pc - \d+', '', regex=True)
#samp_ctr['lemm'] = samp_ctr['lemm'].str.replace('pcd\d+', '', regex=True)
#samp_ctr['lemm'] = samp_ctr['lemm'].str.replace('id \d+', '', regex=True)
#samp_ctr['lemm'] = samp_ctr['lemm'].str.replace('p\d+', '', regex=True)
#samp_ctr['lemm'] = samp_ctr['lemm'].str.replace('\d+', '', regex=True)
#samp_ctr['lemm'] = samp_ctr['lemm'].str.replace('_', ' ', regex=True)
samp_ctr['lemm'] = samp_ctr['lemm'].str.replace('\w*\d\w*', ' ', regex=True)
samp_ctr['lemm'] = samp_ctr['lemm'].str.replace('_', ' ', regex=True)
samp_ctr['lemm'] = samp_ctr['lemm'].str.replace('\W', ' ', regex=True)

In [313]:
#trim(preg_replace("/(^|\s+)(\S(\s+|$))+/", " ", $input));
samp_ctr['lemm'] = samp_ctr['lemm'].str.replace('\\b\\w{1,2}\\b', ' ', regex=True)

In [216]:
samp_Type2s['lemm'] = samp_Type2s['lemm'].str.replace('pc\d+', '', regex=True)
samp_Type2s['lemm'] = samp_Type2s['lemm'].str.replace('pc-\d+', '', regex=True)
samp_Type2s['lemm'] = samp_Type2s['lemm'].str.replace('pc \d+', '', regex=True)
samp_Type2s['lemm'] = samp_Type2s['lemm'].str.replace('pc - \d+', '', regex=True)
samp_Type2s['lemm'] = samp_Type2s['lemm'].str.replace('pcd\d+', '', regex=True)
samp_Type2s['lemm'] = samp_Type2s['lemm'].str.replace('id \d+', '', regex=True)
samp_Type2s['lemm'] = samp_Type2s['lemm'].str.replace('p\d+', '', regex=True)
samp_Type2s['lemm'] = samp_Type2s['lemm'].str.replace('\d+', '', regex=True)
samp_Type2s['lemm'] = samp_Type2s['lemm'].str.replace('\W', ' ', regex=True)

In [ ]:
samp_ctr[samp_ctr['objectBriefDescription'].str.contains('CP\d+')]

In [118]:
samp_Type2s[samp_Type2s['objectBriefDescription'].str.contains('dm\d+')]

Empty DataFrame
Columns: [lemm, ctr_ads, id, contractingProcedureType, contractType, objectBriefDescription, country, parsedPriceBracket, executionDeadlineDays, cpvsSplit, nif, county]
Index: []

In [ ]:
samp_Type2s

# Text Embedding Using distiluse-base-multilingual-cased-v1

# Type1s

In [332]:
samp_ctr['lemm'] = samp_ctr['lemm'].str.strip()
samp_ctr = samp_ctr[samp_ctr['lemm'] != '']
samp_ctr.reset_index(inplace = True,drop = True)

In [387]:
samp_ctr['category1s_text'] = samp_ctr['category1s_text'].str.strip()
samp_ctr = samp_ctr[samp_ctr['category1s_text'] ]
samp_ctr.reset_index(inplace = True,drop = True)

In [395]:
samp_ctr = samp_ctr.fillna('No Info')

In [ ]:
samp_ctr[samp_ctr['category1s_text'] == 'No Info']

In [ ]:
samp_ctr['category1s_text'][samp_ctr.category1s_text.str.contains('Equipamento')]

In [333]:
#Text Embedding for Type1 Titles

from sentence_transformers import SentenceTransformer
model = SentenceTransformer('distiluse-base-multilingual-cased-v1')

start = time.time()
embeddings_ctr_2 = []

n = len(samp_ctr['lemm'])

print(f"There are {n} records to process today")
embeddings_ctr_2 = model.encode(samp_ctr['lemm'])
print(f"{n} records are added")

end = time.time()
# Total time to compute

print('\nThis function took {:.2f} s to compute.'.format(end - start))

There are 10168 records to process today
10168 records are added

This function took 354.93 s to compute.

In [87]:
#Saving the data
embeddings_ctr_2.tofile("./embeddings_ctr_2.csv", sep = ',')

In [ ]:
ctr_embeds_df_2 = pd.DataFrame(embeddings_ctr_2)
ctr_embeds_df_2.columns = ['col_'+str(num) for num in range(embeddings_ctr_2.shape[1])]
ctr_embeds_df_2

#Cleared Output to comply with the NDA

In [398]:
import nltk
import re
from nltk.corpus import stopwords
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
def lemmatize_words(text):
    text = re.sub('[^a-zA-Z]', ' ', text)
    #print(text)
    text = text.lower()
    words = text.split()
    words = [lemmatizer.lemmatize(word,pos='v') for word in words if not word in set(stopwords.words('portuguese'))]
    return ' '.join(words)
samp_ctr['category1s_text_lemm'] = samp_ctr['category1s_text'].apply(lemmatize_words)

[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/uniquenetra/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [ ]:
samp_ctr

In [401]:
#Text Embedding for Type1 category1s

from sentence_transformers import SentenceTransformer
model = SentenceTransformer('distiluse-base-multilingual-cased-v1')

start = time.time()
embeddings_ctr_category1s = []

n = len(samp_ctr['category1s_text'])

print(f"There are {n} records to process today")
embeddings_ctr_category1s = model.encode(samp_ctr['category1s_text_lemm'])
print(f"{n} records are added")

end = time.time()
# Total time to compute

print('\nThis function took {:.2f} s to compute.'.format(end - start))

There are 10168 records to process today
10168 records are added

This function took 146.46 s to compute.

In [ ]:
ctr_embeds_df_category1s = pd.DataFrame(embeddings_ctr_category1s)
ctr_embeds_df_category1s.columns = ['col_'+str(num) for num in range(embeddings_ctr_category1s.shape[1])]
ctr_embeds_df_category1s

#Cleared Output to comply with the NDA

In [75]:
#Text Embedding for Ad Titles

from sentence_transformers import SentenceTransformer
model = SentenceTransformer('distiluse-base-multilingual-cased-v1')

start = time.time()
embeddings_Type2s_2 = []

n = len(samp_Type2s['lemm'])

print(f"There are {n} records to process today")
embeddings_Type2s_2 = model.encode(samp_Type2s['lemm'])
print(f"{n} records are added")

end = time.time()
# Total time to compute

print('\nThis function took {:.2f} s to compute.'.format(end - start))

There are 10224 records to process today
10224 records are added

This function took 502.24 s to compute.

In [76]:
#Saving the data
embeddings_Type2s_2.tofile("./embeddings_Type2s_2.csv", sep = ',')

In [ ]:
Type2s_embeds_df_2 = pd.DataFrame(embeddings_Type2s_2)
Type2s_embeds_df_2.columns = ['col_'+str(num) for num in range(embeddings_Type2s_2.shape[1])]
Type2s_embeds_df_2

#Cleared Output to comply with the NDA

# Build the ANNOY Index Using distiluse-base-multilingual-cased-v1

In [217]:
#Using ANNOY: Approximate Nearest Neighbours Oh yeah! by Spotify for Type1s
from annoy import AnnoyIndex

import time
start = time.time()

f = 512

t_ctr_txt_2 = AnnoyIndex(f, 'angular')  #Length of item vector that will be indexed
#for index, row in dummy_df.head(1000):
   # t.add_item(index, row)
#adf = final_df.iloc[:500000, :]
for index, row in ctr_embeds_df_2.iterrows():
    #print(f"index: {index}, row: {row.nif}")
    t_ctr_txt_2.add_item(index, row)

t_ctr_txt_2.build(10) # 10 trees
t_ctr_txt_2.save('test_ctr_txt_2.ann')

end = time.time()

# Total time to compute
print('\nThis function took {:.2f} s to compute.'.format(end - start))

This function took 16.37 s to compute.

In [ ]:
#Using ANNOY: Approximate Nearest Neighbours Oh yeah! by Spotify for Type2s
from annoy import AnnoyIndex

import time
start = time.time()

f = 512

t_Type2s_txt_2 = AnnoyIndex(f, 'angular')  #Length of item vector that will be indexed
#for index, row in dummy_df.head(1000):
   # t.add_item(index, row)
#adf = final_df.iloc[:500000, :]
for index, row in Type2s_embeds_df_2.iterrows():
    #print(f"index: {index}, row: {row.nif}")
    t_Type2s_txt_2.add_item(index, row)

t_Type2s_txt_2.build(10) # 10 trees
t_Type2s_txt_2.save('test_Type2s_txt_2.ann')

end = time.time()

# Total time to compute
print('\nThis function took {:.2f} s to compute.'.format(end - start))

# Testing the embeddings distiluse-base-multilingual-cased-v1: Type1s

In [109]:
#TC1
c_no = <> #Info removed to comply with the NDA 
c_list = [<>] #Info removed to comply with the NDA


indx = samp_ctr.index[samp_ctr['id'] == c_no].tolist()
print(f"Type1 No.: {c_no} index: {indx}")
print("\nIndexes of Type1s to be matched: ")
print(samp_ctr[samp_ctr['id'].isin(c_list)]['id'])
lst = samp_ctr[samp_ctr['id'].isin(c_list)].index

u = AnnoyIndex(f, 'angular')
u.load('test_ctr_txt_2.ann') # super fast, will just mmap the file
result = pd.DataFrame()
result['Col1'] = pd.DataFrame(u.get_nns_by_item(indx[0], 500 )) # will find the 1000 nearest neighbors
print("\nMatch Results")
res = result[result['Col1'].isin(lst)].Col1
print(f"{len(res)} records match")
res

Contract No.: 9054597 index: [10168]

Indexes of Contracts to be matched:
10054    7666846
10061    7724046
10164    9253429
Name: id, dtype: int64

Match Results
1 records match

2    10164
Name: Col1, dtype: int64

In [ ]:
#TC1
#To view the full list of result
u = AnnoyIndex(f, 'angular')
u.load('test_ctr_txt_2.ann') # super fast, will just mmap the file
result = pd.DataFrame()
result = u.get_nns_by_item(<>, 10 ) # will find the 1000 nearest neighbors #Info removed to comply with the NDA

#result.sort()
print(result)

#Cleared Output to comply with the NDA

In [ ]:
#TC1
samp_ctr[samp_ctr.index.isin([<>])] #Info removed to comply with the NDA

#Cleared Output to comply with the NDA

In [ ]:
#TC2
c_no = <> #Info removed to comply with the NDA
c_list = [<>] #Info removed to comply with the NDA


indx = samp_ctr.index[samp_ctr['id'] == c_no].tolist()
print(f"Type1 No.: {c_no} index: {indx}")
print("\nIndexes of Type1s to be matched: ")
print(samp_ctr[samp_ctr['id'].isin(c_list)]['id'])
lst = samp_ctr[samp_ctr['id'].isin(c_list)].index

u = AnnoyIndex(f, 'angular')
u.load('test_ctr_txt_2.ann') # super fast, will just mmap the file
result = pd.DataFrame()
result['Col1'] = pd.DataFrame(u.get_nns_by_item(indx[0], 5000 )) # will find the 1000 nearest neighbors
print("\nMatch Results")
res = result[result['Col1'].isin(lst)].Col1
print(f"{len(res)} records match")
res

#Cleared Output to comply with the NDA

In [ ]:
#TC2
#To view the full list of result
u = AnnoyIndex(f, 'angular')
u.load('test_ctr_txt_2.ann') # super fast, will just mmap the file
result = pd.DataFrame()
result = u.get_nns_by_item(<>, 10 ) # will find the 1000 nearest neighbors #Info removed to comply with the NDA

#result.sort()
print(result)

#Cleared Output to comply with the NDA

In [850]:
#TC2
samp_ctr[samp_ctr.index.isin([10128, 10082, 10130, 10152])]

,lemm,ctr_ads,id,contractingProcedureType,contractType,objectBriefDescription,country,parsedPriceBracket,executionDeadlineDays,cpvsSplit,nif,county
10082,servico mapeamento necessidade competencia are...,1,6407988,Ajuste Direto Regime Geral,Aquisição de serviços,serviços de mapeamento de necessidades de comp...,49,1,3,6680,4375,-1
10128,subscricao catalogo atividade parar desenvolvi...,1,7373595,Ajuste Direto Regime Geral,Aquisição de bens móveis,Subscrição de catálogo de atividades para dese...,49,1,11,786,121,70
10130,adesao rede parceiro parar desenvolvimento loc...,1,7495110,Ajuste Direto Regime Geral,Aquisição de serviços,Adesão à rede de parceiros para o desenvolvime...,49,1,11,6583,986,117
10152,subscricao acesso revista cientifico (varios l...,1,6307468,Concurso público,Aquisição de bens móveis,Subscrição do acesso a revistas científicas (v...,49,1,9,775,1130,117

In [ ]:
#TC2
samp_ctr[samp_ctr.index.isin([<>])]#Info removed to comply with the NDA

In [ ]:
#TC3
c_no = <>
c_list = [<>] #Info removed to comply with the NDA


indx = final_ctr.index[final_ctr['id'] == c_no].tolist()
print(f"Type1 No.: {c_no} index: {indx}")
indx = final_ctr.index[final_ctr['id'] == c_no].tolist()
print(f"Type1 No.: {c_no} index: {indx}")
print("\nIndexes of Type1s to be matched: ")
print(final_ctr[final_ctr['id'].isin(c_list)]['id'])
lst = final_ctr[final_ctr['id'].isin(c_list)].index

u = AnnoyIndex(f, 'angular')
u.load('test_ctr_txt_2.ann') # super fast, will just mmap the file
result = pd.DataFrame()
result['Col1'] = pd.DataFrame(u.get_nns_by_item(indx[0], 1000 )) # will find the 1000 nearest neighbors
print("\nMatch Results")
res = result[result['Col1'].isin(lst)].Col1
print(f"{len(res)} records match")
res

#Cleared Output to comply with the NDA

In [ ]:
#TC3
#To view the full list of result
u = AnnoyIndex(f, 'angular')
u.load('test_ctr_txt_2.ann') # super fast, will just mmap the file
result = pd.DataFrame()
result = u.get_nns_by_item(<>, 10 ) # will find the 1000 nearest neighbors #Info removed to comply with the NDA

#result.sort()
print(result)

#Cleared Output to comply with the NDA

In [ ]:
#TC3
samp_ctr[samp_ctr.index.isin([<>])]#Info removed to comply with the NDA

#Cleared Output to comply with the NDA

# Testing the embeddings distiluse-base-multilingual-cased-v1: Type2s

In [ ]:
#TC1
a_no = <>
a_list = [<>]
indx = samp_Type2s.index[samp_Type2s['id'] == a_no].tolist()
print(f"Ad No.: {a_no} index: {indx}")
print("\nIndexes of Type2s to be matched: ")
print(samp_Type2s[samp_Type2s['id'].isin(a_list)]['id'])
lst = samp_Type2s[samp_Type2s['id'].isin(a_list)].index

u = AnnoyIndex(f, 'angular')
u.load('test_Type2s_txt_2.ann') # super fast, will just mmap the file
result = pd.DataFrame()
result['Col1'] = pd.DataFrame(u.get_nns_by_item(indx[0], 4000 )) # will find the 1000 nearest neighbors
print("\nMatch Results")
res = result[result['Col1'].isin(lst)].Col1
print(f"{len(res)} records match")
res

#Cleared Output to comply with the NDA

In [ ]:
#TC1
#To view the full list of result
u = AnnoyIndex(f, 'angular')
u.load('test_Type2s_txt_2.ann') # super fast, will just mmap the file
result = pd.DataFrame()
result = u.get_nns_by_item(<>, 10 ) # will find the 1000 nearest neighbors

#result.sort()
print(result)

#Cleared Output to comply with the NDA

In [ ]:
#TC1
samp_Type2s[samp_Type2s.index.isin([<>])]

#Cleared Output to comply with the NDA

In [ ]:
#TC2
a_no = <>
a_list = []
indx = samp_Type2s.index[samp_Type2s['id'] == a_no].tolist()
print(f"Ad No.: {a_no} index: {indx}")
print("\nIndexes of Type2s to be matched: ")
print(samp_Type2s[samp_Type2s['id'].isin(a_list)]['id'])
lst = samp_Type2s[samp_Type2s['id'].isin(a_list)].index

u = AnnoyIndex(f, 'angular')
u.load('test_Type2s_txt_2.ann') # super fast, will just mmap the file
result = pd.DataFrame()
result['Col1'] = pd.DataFrame(u.get_nns_by_item(indx[0], 5000 )) # will find the 1000 nearest neighbors
print("\nMatch Results")
res = result[result['Col1'].isin(lst)].Col1
print(f"{len(res)} records match")
res

#Cleared Output to comply with the NDA

In [ ]:
#TC2
#To view the full list of result
u = AnnoyIndex(f, 'angular')
u.load('test_Type2s_txt_2.ann') # super fast, will just mmap the file
result = pd.DataFrame()
result = u.get_nns_by_item(<>, 10 ) # will find the 1000 nearest neighbors 

#result.sort()
print(result)

#Cleared Output to comply with the NDA

In [ ]:
#TC2
samp_Type2s[samp_Type2s.index.isin([<>])] 

#Cleared Output to comply with the NDA

# Trial 2 features - text, category1ssplit : Type1s

In [853]:
#Replacing text with the embeddings for Type1s : multilingual
final_ctr = pd.concat([ctr_embeds_df_2, samp_ctr['category1sSplit']], axis=1)
#final_ctr = final_ctr.drop(columns = ['lemm'])
final_ctr

,col_0,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,...,col_503,col_504,col_505,col_506,col_507,col_508,col_509,col_510,col_511,cpvsSplit
0,-0.008769,-0.035696,-0.081959,-0.065422,0.106423,-0.006806,0.014415,-0.019768,-0.007022,0.022455,...,-0.004052,0.065656,-0.080810,0.016209,-0.011536,0.013828,0.040486,0.051302,0.014021,4690
1,0.041093,-0.032101,-0.062681,-0.027410,0.083845,-0.030770,-0.019008,-0.087988,0.053893,0.023575,...,-0.008800,0.037727,-0.035784,0.050928,-0.014732,-0.041200,0.017684,-0.089092,0.001281,4698
2,0.026384,-0.036660,0.010439,0.003870,-0.000859,0.011253,-0.004238,-0.006598,-0.041758,-0.015051,...,-0.013433,-0.012822,-0.015036,-0.095395,-0.002170,-0.000507,-0.061892,0.020786,-0.019073,4708
3,0.013121,-0.041674,-0.012382,-0.035365,0.101415,0.027916,0.009208,-0.016659,0.002207,0.010975,...,-0.024724,-0.014496,-0.037792,0.022144,-0.045335,-0.020217,-0.001707,0.073547,0.006090,4724
4,0.006715,-0.055337,0.003673,-0.004573,0.057083,0.051284,0.037291,-0.038526,-0.037250,0.031229,...,0.038382,-0.078159,0.047688,0.032358,0.024627,-0.033376,0.013414,-0.022359,0.049040,4703
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10198,-0.019831,0.004905,0.027139,-0.016492,-0.058190,0.028122,-0.017875,0.019658,-0.020580,-0.023857,...,-0.041780,-0.004194,0.009265,-0.030309,0.020870,0.053502,0.048767,-0.002036,-0.012913,2583
10199,-0.025081,-0.052650,-0.045189,-0.000725,-0.001611,0.042363,-0.022679,0.031628,0.016473,-0.020218,...,-0.007561,0.009151,-0.000184,-0.002363,0.003779,-0.002796,0.112329,0.023464,-0.030824,4320
10200,0.007497,0.047767,-0.001658,-0.026412,0.055747,-0.010143,0.070942,0.019195,-0.034207,0.040163,...,0.001890,0.012175,0.001437,0.017530,0.021713,0.050491,-0.057415,-0.008700,-0.009758,597
10201,0.007973,-0.006567,0.007972,-0.024185,0.037945,-0.024951,0.021616,0.010492,-0.025213,0.039273,...,-0.075808,-0.054949,0.004109,0.009871,0.007268,0.058270,0.018326,0.012770,0.049915,3051
10202,0.006300,-0.034266,-0.021577,-0.033345,0.005970,0.015349,-0.009623,-0.016358,-0.022686,0.004165,...,-0.022496,-0.006637,-0.033977,0.061615,0.003057,0.069206,-0.045256,0.009401,0.048284,127

# Build the ANNOY Index for 2 features : Type1s

In [854]:
#Using ANNOY: Approximate Nearest Neighbours Oh yeah! by Spotify for Type1s
from annoy import AnnoyIndex

import time
start = time.time()

f = 513

t_ctr_ftr_2 = AnnoyIndex(f, 'angular')  #Length of item vector that will be indexed
#for index, row in dummy_df.head(1000):
   # t.add_item(index, row)
#adf = final_df.iloc[:500000, :]
for index, row in final_ctr.iterrows():
    #print(f"index: {index}, row: {row.nif}")
    t_ctr_ftr_2.add_item(index, row)

t_ctr_ftr_2.build(10) # 10 trees
t_ctr_ftr_2.save('test_ctr_ftr_2.ann')

end = time.time()

# Total time to compute
print('\nThis function took {:.2f} s to compute.'.format(end - start))

This function took 16.75 s to compute.

# Testing 2 features : Type1s

In [ ]:
#TC1
c_no = <>
c_list = [<>]


indx = samp_ctr.index[samp_ctr['id'] == c_no].tolist()
print(f"Type1 No.: {c_no} index: {indx}")
print("\nIndexes of Type1s to be matched: ")
print(samp_ctr[samp_ctr['id'].isin(c_list)]['id'])
lst = samp_ctr[samp_ctr['id'].isin(c_list)].index

u = AnnoyIndex(f, 'angular')
u.load('test_ctr_ftr_2.ann') # super fast, will just mmap the file
result = pd.DataFrame()
result['Col1'] = pd.DataFrame(u.get_nns_by_item(indx[0], 7000 )) # will find the 1000 nearest neighbors
print("\nMatch Results")
res = result[result['Col1'].isin(lst)].Col1
print(f"{len(res)} records match")
res

#Cleared Output to comply with the NDA

In [ ]:
#TC1
#To view the full list of result
u = AnnoyIndex(f, 'angular')
u.load('test_ctr_ftr_2.ann') # super fast, will just mmap the file
result = pd.DataFrame()
result = u.get_nns_by_item(<>, 10 ) # will find the 1000 nearest neighbors

#result.sort()
print(result)

#Cleared Output to comply with the NDA

In [ ]:
#TC1
samp_ctr[samp_ctr.index.isin([<>])] #Cleared Output to comply with the NDA

# Trial weighted features - text, category1ssplit, nif, parsedPriceBracket : Type1s

In [454]:
#Replacing text with the embeddings for Type1s : multilingual
final_ctr = pd.concat([ctr_embeds_df_2 * 0.6, ctr_embeds_df_category1s * 0.35, samp_ctr['parsedPriceBracket'] * 0.05,  samp_ctr['nif'] * 0], axis=1)
#final_ctr = final_ctr.drop(columns = ['lemm'])
final_ctr

,col_0,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,...,col_504,col_505,col_506,col_507,col_508,col_509,col_510,col_511,parsedPriceBracket,nif
0,-0.016792,-0.018643,-0.039004,-0.029895,0.054194,-0.019316,0.007323,-0.017478,0.001804,0.012764,...,0.036609,0.009088,-0.010209,-0.025550,0.011412,-0.001523,0.000394,0.012107,0.05,0
1,0.018126,-0.017007,-0.033536,-0.010536,0.041234,-0.041406,-0.014353,-0.061255,0.034637,0.015067,...,0.028621,-0.013683,-0.002110,-0.008999,-0.001672,0.011201,0.001808,0.015103,0.05,0
2,0.015830,-0.021996,0.006263,0.002322,-0.000516,0.006752,-0.002543,-0.003959,-0.025055,-0.009030,...,0.031862,0.002847,-0.023262,-0.007924,0.011927,-0.011813,0.003423,0.005073,0.05,0
3,-0.008573,-0.027852,0.002949,-0.021954,0.046245,-0.009400,0.007797,-0.017694,-0.005431,0.001391,...,0.035916,-0.000432,-0.021911,0.008485,0.018192,0.007023,0.000096,0.025782,0.05,0
4,0.004029,-0.033202,0.002204,-0.002744,0.034250,0.030770,0.022375,-0.023115,-0.022350,0.018738,...,0.020884,0.009681,0.002245,-0.035181,-0.002482,-0.004843,-0.011499,0.005506,0.05,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10163,-0.008608,-0.000429,0.020157,-0.012266,0.046668,-0.017598,-0.003401,0.010460,-0.023512,-0.005675,...,-0.014046,0.015082,-0.007095,0.008758,0.012790,-0.007523,-0.016513,-0.012945,0.05,0
10164,-0.011846,-0.022739,-0.022890,-0.013924,0.049583,0.007865,-0.008198,0.012502,0.017764,-0.000175,...,0.012753,0.010746,-0.024242,-0.042271,-0.010351,-0.016525,-0.010162,-0.004336,0.05,0
10165,0.004498,0.028660,-0.000995,-0.015847,0.033448,-0.006086,0.042565,0.011517,-0.020524,0.024098,...,-0.021228,0.011940,-0.004379,0.011598,0.023775,-0.008921,-0.001624,-0.030797,0.05,0
10166,0.004784,-0.003940,0.004783,-0.014511,0.022767,-0.014971,0.012970,0.006295,-0.015128,0.023564,...,-0.023020,0.003051,-0.007237,-0.001841,0.022719,-0.002490,0.008838,-0.008453,0.05,0
10167,0.003780,-0.020559,-0.012946,-0.020007,0.003582,0.009210,-0.005774,-0.009815,-0.013612,0.002499,...,0.016069,-0.004513,0.005644,-0.014978,0.018789,-0.013017,-0.003252,0.019314,0.10,0

In [529]:
final_ctr.shape[1]

1026

# Build the ANNOY index using weighted features : Type1s

In [455]:
#Using ANNOY: Approximate Nearest Neighbours Oh yeah! by Spotify for Type1s
from annoy import AnnoyIndex

import time
start = time.time()

f = 1026

t_ctr_ftr_2_wt = AnnoyIndex(f, 'angular')  #Length of item vector that will be indexed
#for index, row in dummy_df.head(1000):
   # t.add_item(index, row)
#adf = final_df.iloc[:500000, :]
for index, row in final_ctr.iterrows():
    #print(f"index: {index}, row: {row.nif}")
    t_ctr_ftr_2_wt.add_item(index, row)

t_ctr_ftr_2_wt.build(10) # 10 trees
t_ctr_ftr_2_wt.save('test_ctr_ftr_2_wt.ann')

end = time.time()

# Total time to compute
print('\nThis function took {:.2f} s to compute.'.format(end - start))

This function took 21.42 s to compute.

# Testing weighted features : Type1s

In [ ]:
#TC1
c_no = <>
c_list = [<>]


indx = samp_ctr.index[samp_ctr['id'] == c_no].tolist()
print(f"Type1 No.: {c_no} index: {indx}")
print("\nIndexes of Type1s to be matched: ")
print(samp_ctr[samp_ctr['id'].isin(c_list)]['id'])
lst = samp_ctr[samp_ctr['id'].isin(c_list)].index

u = AnnoyIndex(f, 'angular')
u.load('test_ctr_ftr_2_wt.ann') # super fast, will just mmap the file
result = pd.DataFrame()
result['Col1'] = pd.DataFrame(u.get_nns_by_item(indx[0], 1000 )) # will find the 1000 nearest neighbors
print("\nMatch Results")
res = result[result['Col1'].isin(lst)].Col1
print(f"{len(res)} records match")
res

#Cleared Output to comply with the NDA

In [ ]:
#TC1
#To view the full list of result
u = AnnoyIndex(f, 'angular')
u.load('test_ctr_ftr_2_wt.ann') # super fast, will just mmap the file
result = pd.DataFrame()
result = u.get_nns_by_item(<>, 10 ) # will find the 1000 nearest neighbors

#result.sort()
print(result)

#Cleared Output to comply with the NDA

In [ ]:
#TC1
samp_ctr[['id', 'objectBriefDescription', 'lemm', 'category1sSplit','category1s_text', 'nif', 'parsedPriceBracket']][samp_ctr.index.isin([10019, 10026, 10130, 10133, 10041, 8071, 617, 10161, 10130, 9999, 10079, 688, 682])]

In [ ]:
#TC1
samp_ctr[['id', 'objectBriefDescription', 'lemm', 'category1sSplit', 'category1s_text', 'nif', 'parsedPriceBracket']][samp_ctr.index.isin([10054, 10161, 10164, 2029, 2409, 3335, 3159, 2399, 1501, 3356, 2387])]

In [ ]:
#TC2
c_no = <>
c_list = [<>]


indx = samp_ctr.index[samp_ctr['id'] == c_no].tolist()
print(f"Type1 No.: {c_no} index: {indx}")
print("\nIndexes of Type1s to be matched: ")
print(samp_ctr[samp_ctr['id'].isin(c_list)]['id'])
lst = samp_ctr[samp_ctr['id'].isin(c_list)].index

u = AnnoyIndex(f, 'angular')
u.load('test_ctr_ftr_2_wt.ann') # super fast, will just mmap the file
result = pd.DataFrame()
result['Col1'] = pd.DataFrame(u.get_nns_by_item(indx[0], 500 )) # will find the 1000 nearest neighbors
print("\nMatch Results")
res = result[result['Col1'].isin(lst)].Col1
print(f"{len(res)} records match")
res

#Cleared Output to comply with the NDA

In [ ]:
#TC2
#To view the full list of result
u = AnnoyIndex(f, 'angular')
u.load('test_ctr_ftr_2_wt.ann') # super fast, will just mmap the file
result = pd.DataFrame()
result = u.get_nns_by_item(<>, 10 ) # will find the 1000 nearest neighbors

#result.sort()
print(result)

#Cleared Output to comply with the NDA

In [ ]:
#TC2
samp_ctr[['id', 'objectBriefDescription', 'lemm', 'category1sSplit', 'category1s_text', 'nif', 'parsedPriceBracket']][samp_ctr.index.isin([10011, 10018, 10102, 10147, 8928, 9782, 7516, 10018, 5895, 5880, 7543, 1781, 8392])]

# Trial weighted features - text, category1ssplit, nif, parsedPriceBracket : Type2s

In [981]:
#Replacing text with the embeddings for Type2s
final_Type2s = pd.concat([Type2s_embeds_df_2 * 0.9, samp_Type2s['parsedPriceBracket'] * 0.1, samp_Type2s['category1sSplit'] * 0, samp_Type2s['nif'] * 0], axis=1)
#final_Type2s = final_Type2s.drop(columns = ['lemm'])
final_Type2s

,col_0,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,...,col_505,col_506,col_507,col_508,col_509,col_510,col_511,parsedPriceBracket,cpvsSplit,nif
0,-0.024220,-0.045912,-0.020986,-0.008549,0.054871,0.013257,-0.008021,-0.067579,0.003622,0.005795,...,0.004481,0.029657,-0.005545,0.016505,0.022840,0.039504,0.036913,0.2,0,0
1,0.076048,0.037826,0.017801,-0.018255,0.086328,-0.018215,0.060745,-0.028341,0.031218,0.030642,...,0.004697,-0.047096,-0.050770,0.023003,0.012869,-0.017902,-0.072109,0.1,0,0
2,0.026081,0.005757,-0.016483,-0.060839,0.064346,-0.034761,-0.029246,-0.007448,0.040436,0.019701,...,-0.000148,0.017771,-0.038433,-0.020825,0.042849,-0.019691,-0.043829,0.1,0,0
3,-0.054735,-0.022269,0.010686,-0.035819,0.021901,0.076630,-0.012732,-0.019730,-0.029121,-0.002356,...,-0.046156,0.020172,-0.011376,0.044809,0.029195,0.031821,0.048732,0.1,0,0
4,0.001414,0.046565,0.073109,0.023697,0.014041,-0.046530,0.004635,0.046016,0.004140,0.000998,...,-0.100692,0.013127,-0.025101,-0.064973,-0.006318,-0.028992,-0.024700,0.1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10219,-0.029705,-0.024705,-0.025263,0.015487,0.093688,0.022982,-0.011590,-0.013941,-0.040275,0.045163,...,0.063992,0.040280,-0.019289,0.035681,-0.022211,-0.026217,-0.002171,0.1,0,0
10220,-0.041041,0.013317,0.035926,-0.053735,0.024570,0.011895,0.005424,0.001817,-0.012700,-0.039497,...,0.014541,0.036006,0.020576,0.008361,0.016710,-0.008317,0.080487,0.2,0,0
10221,-0.005121,0.031187,-0.039318,-0.066958,0.071893,0.008878,0.008889,-0.011997,0.028955,0.000701,...,-0.015090,-0.017232,-0.037847,0.002226,0.034090,0.015655,-0.050307,0.1,0,0
10222,-0.008070,0.043932,-0.028641,-0.008111,0.107252,-0.011243,0.012140,-0.034764,-0.049123,0.012485,...,0.078929,0.006864,-0.030277,0.021937,0.052737,0.056380,-0.001355,0.3,0,0
10223,-0.002255,0.085448,0.039749,-0.067235,0.068298,0.053565,0.006981,-0.006713,-0.087817,0.022560,...,0.001602,-0.041276,-0.011615,0.027237,0.028706,0.043702,0.048434,0.2,0,0

# Build the ANNOY index using weighted features : Type2s

In [982]:
#Using ANNOY: Approximate Nearest Neighbours Oh yeah! by Spotify for Type2s
from annoy import AnnoyIndex

import time
start = time.time()

f = 515

t_Type2s_ftr_2_wt = AnnoyIndex(f, 'angular')  #Length of item vector that will be indexed
#for index, row in dummy_df.head(1000):
   # t.add_item(index, row)
#adf = final_df.iloc[:500000, :]
for index, row in final_Type2s.iterrows():
    #print(f"index: {index}, row: {row.nif}")
    t_Type2s_ftr_2_wt.add_item(index, row)

t_Type2s_ftr_2_wt.build(10) # 10 trees
t_Type2s_ftr_2_wt.save('test_Type2s_ftr_2_wt.ann')

end = time.time()

# Total time to compute
print('\nThis function took {:.2f} s to compute.'.format(end - start))

This function took 15.97 s to compute.

# Testing weighted features : Type2s

In [ ]:
#TC1
a_no = <>
a_list = [<>]
indx = samp_Type2s.index[samp_Type2s['id'] == a_no].tolist()
print(f"Ad No.: {a_no} index: {indx}")
print("\nIndexes of Type2s to be matched: ")
print(samp_Type2s[samp_Type2s['id'].isin(a_list)]['id'])
lst = samp_Type2s[samp_Type2s['id'].isin(a_list)].index

u = AnnoyIndex(f, 'angular')
u.load('test_Type2s_ftr_2_wt.ann') # super fast, will just mmap the file
result = pd.DataFrame()
result['Col1'] = pd.DataFrame(u.get_nns_by_item(indx[0], 2600 )) # will find the 1000 nearest neighbors
print("\nMatch Results")
res = result[result['Col1'].isin(lst)].Col1
print(f"{len(res)} records match")
res

#Cleared Output to comply with the NDA

In [ ]:
#TC2
a_no = <>
a_list = [<>]
indx = samp_Type2s.index[samp_Type2s['id'] == a_no].tolist()
print(f"Ad No.: {a_no} index: {indx}")
print("\nIndexes of Type2s to be matched: ")
print(samp_Type2s[samp_Type2s['id'].isin(a_list)]['id'])
lst = samp_Type2s[samp_Type2s['id'].isin(a_list)].index

u = AnnoyIndex(f, 'angular')
u.load('test_Type2s_ftr_2_wt.ann') # super fast, will just mmap the file
result = pd.DataFrame()
result['Col1'] = pd.DataFrame(u.get_nns_by_item(indx[0], 1950 )) # will find the 1000 nearest neighbors
print("\nMatch Results")
res = result[result['Col1'].isin(lst)].Col1
print(f"{len(res)} records match")
res

#Cleared Output to comply with the NDA

# Trial all features : Type1s

In [ ]:
samp_ctr

In [97]:
#Replacing text with the embeddings for Type1s : multilingual
final_ctr = pd.concat([ctr_embeds_df_2*.9, samp_ctr['parsedPriceBracket']*.1, samp_ctr['category1sSplit']*0, samp_ctr['nif']*0,  samp_ctr['Type1Type'], samp_ctr['country']*0 ], axis=1)
#samp_ctr['Type1ingProcedureType']*0,
#final_ctr = final_ctr.drop(columns = ['lemm'])
final_ctr

,col_0,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,...,col_507,col_508,col_509,col_510,col_511,parsedPriceBracket,cpvsSplit,nif,contractType,country
0,-0.025188,-0.027965,-0.058506,-0.044843,0.081290,-0.028974,0.010984,-0.026217,0.002706,0.019146,...,-0.003772,0.014956,0.043034,0.021761,0.018051,0.1,0,0,Empreitadas de obras públicas,0
1,0.027189,-0.025510,-0.050304,-0.015804,0.061851,-0.062109,-0.021529,-0.091883,0.051956,0.022601,...,-0.002431,-0.038368,0.018954,-0.119253,-0.006458,0.1,0,0,Empreitadas de obras públicas,0
2,0.023746,-0.032994,0.009395,0.003483,-0.000773,0.010128,-0.003814,-0.005938,-0.037582,-0.013546,...,-0.001953,-0.000456,-0.055703,0.018707,-0.017165,0.1,0,0,Empreitadas de obras públicas,0
3,-0.012859,-0.041778,0.004424,-0.032930,0.069367,-0.014100,0.011696,-0.026541,-0.008146,0.002086,...,-0.026605,-0.016850,0.009539,0.029777,-0.006781,0.1,0,0,Empreitadas de obras públicas,0
4,0.006043,-0.049803,0.003306,-0.004116,0.051375,0.046155,0.033562,-0.034673,-0.033525,0.028106,...,0.022164,-0.030039,0.012072,-0.020123,0.044136,0.1,0,0,Empreitadas de obras públicas,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10198,-0.005465,-0.006654,0.038080,-0.026083,0.031696,-0.006419,-0.034606,0.019542,-0.019114,-0.006628,...,0.024234,0.047100,0.038359,-0.001135,-0.013706,0.1,0,0,Aquisição de bens móveis,0
10199,-0.011662,-0.039156,-0.026785,-0.021801,0.027409,0.009786,-0.011875,0.021311,0.031874,-0.009141,...,0.016894,0.001043,0.089262,0.011554,-0.038507,0.1,0,0,Concessão de obras públicas,0
10200,0.006748,0.042990,-0.001492,-0.023771,0.050172,-0.009129,0.063847,0.017276,-0.030787,0.036147,...,0.019542,0.045442,-0.051673,-0.007830,-0.008782,0.1,0,0,Aquisição de bens móveis,0
10201,0.007176,-0.005910,0.007175,-0.021767,0.034151,-0.022456,0.019454,0.009442,-0.022692,0.035346,...,0.006541,0.052443,0.016494,0.011493,0.044924,0.1,0,0,Aquisição de bens móveis,0
10202,0.005670,-0.030839,-0.019419,-0.030010,0.005373,0.013814,-0.008660,-0.014722,-0.020418,0.003749,...,0.002751,0.062285,-0.040730,0.008461,0.043456,0.2,0,0,Aquisição de bens móveis,0

In [98]:
#Converting categorical data into dummy or indicator variables for Type1s
final_ctr = pd.get_dummies(final_ctr, prefix={#'Type1ingProcedureType':'Type1ingProcedureType', 
                                              'Type1Type':'Type1Type'}, 
                                              columns = [#'Type1ingProcedureType', 
                                                         'Type1Type'],
                          drop_first=True)
final_ctr

,col_0,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,...,country,contractType_Aquisição de bens móveis<br/>Aquisição de serviços,contractType_Aquisição de bens móveis<br/>Empreitadas de obras públicas,contractType_Aquisição de serviços,contractType_Aquisição de serviços<br/>Aquisição de bens móveis,contractType_Aquisição de serviços<br/>Locação de bens móveis,contractType_Concessão de obras públicas,contractType_Empreitadas de obras públicas,contractType_Locação de bens móveis,contractType_Sociedade<br/>Aquisição de serviços
0,-0.025188,-0.027965,-0.058506,-0.044843,0.081290,-0.028974,0.010984,-0.026217,0.002706,0.019146,...,0,0,0,0,0,0,0,1,0,0
1,0.027189,-0.025510,-0.050304,-0.015804,0.061851,-0.062109,-0.021529,-0.091883,0.051956,0.022601,...,0,0,0,0,0,0,0,1,0,0
2,0.023746,-0.032994,0.009395,0.003483,-0.000773,0.010128,-0.003814,-0.005938,-0.037582,-0.013546,...,0,0,0,0,0,0,0,1,0,0
3,-0.012859,-0.041778,0.004424,-0.032930,0.069367,-0.014100,0.011696,-0.026541,-0.008146,0.002086,...,0,0,0,0,0,0,0,1,0,0
4,0.006043,-0.049803,0.003306,-0.004116,0.051375,0.046155,0.033562,-0.034673,-0.033525,0.028106,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10198,-0.005465,-0.006654,0.038080,-0.026083,0.031696,-0.006419,-0.034606,0.019542,-0.019114,-0.006628,...,0,0,0,0,0,0,0,0,0,0
10199,-0.011662,-0.039156,-0.026785,-0.021801,0.027409,0.009786,-0.011875,0.021311,0.031874,-0.009141,...,0,0,0,0,0,0,1,0,0,0
10200,0.006748,0.042990,-0.001492,-0.023771,0.050172,-0.009129,0.063847,0.017276,-0.030787,0.036147,...,0,0,0,0,0,0,0,0,0,0
10201,0.007176,-0.005910,0.007175,-0.021767,0.034151,-0.022456,0.019454,0.009442,-0.022692,0.035346,...,0,0,0,0,0,0,0,0,0,0
10202,0.005670,-0.030839,-0.019419,-0.030010,0.005373,0.013814,-0.008660,-0.014722,-0.020418,0.003749,...,0,0,0,0,0,0,0,0,0,0

# Build the ANNOY index using all features : Type1s

In [112]:
#Using ANNOY: Approximate Nearest Neighbours Oh yeah! by Spotify for Type1s
from annoy import AnnoyIndex

import time
start = time.time()

f = 525

t_ctr_all_ftrs = AnnoyIndex(f, 'angular')  #Length of item vector that will be indexed
#for index, row in dummy_df.head(1000):
   # t.add_item(index, row)
#adf = final_df.iloc[:500000, :]
for index, row in final_ctr.iterrows():
    #print(f"index: {index}, row: {row.nif}")
    t_ctr_all_ftrs.add_item(index, row)

t_ctr_all_ftrs.build(10) # 10 trees
t_ctr_all_ftrs.save('test_ctr_all_ftrs.ann')

end = time.time()

# Total time to compute
print('\nThis function took {:.2f} s to compute.'.format(end - start))

This function took 10.55 s to compute.

# Testing with all the features : Type1s

In [ ]:
#TC1
c_no = <>
c_list = [<>]


indx = samp_ctr.index[samp_ctr['id'] == c_no].tolist()
print(f"Type1 No.: {c_no} index: {indx}")
print("\nIndexes of Type1s to be matched: ")
print(samp_ctr[samp_ctr['id'].isin(c_list)]['id'])
lst = samp_ctr[samp_ctr['id'].isin(c_list)].index

u = AnnoyIndex(f, 'angular')
u.load('test_ctr_all_ftrs.ann') # super fast, will just mmap the file
result = pd.DataFrame()
result['Col1'] = pd.DataFrame(u.get_nns_by_item(indx[0], 1000 )) # will find the 1000 nearest neighbors
print("\nMatch Results")
res = result[result['Col1'].isin(lst)].Col1
print(f"{len(res)} records match")
res

#Cleared Output to comply with the NDA

In [ ]:
#TC1
#To view the full list of result
u = AnnoyIndex(f, 'angular')
u.load('test_ctr_all_ftrs.ann') # super fast, will just mmap the file
result = pd.DataFrame()
result = u.get_nns_by_item(<>, 10 ) # will find the 1000 nearest neighbors

#result.sort()
print(result)

#Cleared Output to comply with the NDA

In [ ]:
#TC1
samp_ctr[['id', 'objectBriefDescription', 'lemm', 'category1sSplit', 'nif', 'parsedPriceBracket', 'Type1Type']][samp_ctr.index.isin([10168, 620, 10164, 693, 687, 3241, 680, 8098, 9009, 2029])]

In [ ]:
#TC2
c_no = <>
c_list = [<>]


indx = samp_ctr.index[samp_ctr['id'] == c_no].tolist()
print(f"Type1 No.: {c_no} index: {indx}")
print("\nIndexes of Type1s to be matched: ")
print(samp_ctr[samp_ctr['id'].isin(c_list)]['id'])
lst = samp_ctr[samp_ctr['id'].isin(c_list)].index

u = AnnoyIndex(f, 'angular')
u.load('test_ctr_all_ftrs.ann') # super fast, will just mmap the file
result = pd.DataFrame()
result['Col1'] = pd.DataFrame(u.get_nns_by_item(indx[0], 500 )) # will find the 1000 nearest neighbors
print("\nMatch Results")
res = result[result['Col1'].isin(lst)].Col1
print(f"{len(res)} records match")
res

#Cleared Output to comply with the NDA

# Trial all features : Type2s

In [ ]:
samp_ctr

In [1016]:
#Replacing text with the embeddings for Type2s
final_Type2s = pd.concat([Type2s_embeds_df_2, samp_Type2s['parsedPriceBracket'], samp_Type2s['category1sSplit'], samp_Type2s['nif'], samp_Type2s['Type1Type'], samp_Type2s['country']], axis=1)
#final_Type2s = final_Type2s.drop(columns = ['lemm'])
final_Type2s

,col_0,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,...,col_507,col_508,col_509,col_510,col_511,parsedPriceBracket,cpvsSplit,nif,contractType,country
0,-0.026911,-0.051014,-0.023318,-0.009499,0.060968,0.014730,-0.008912,-0.075087,0.004025,0.006439,...,-0.006161,0.018339,0.025377,0.043894,0.041015,2,5625,50,NA,43
1,0.084498,0.042029,0.019779,-0.020284,0.095920,-0.020238,0.067495,-0.031489,0.034687,0.034047,...,-0.056411,0.025558,0.014299,-0.019891,-0.080121,1,6574,2886,Aquisição de serviços,43
2,0.028979,0.006396,-0.018315,-0.067599,0.071495,-0.038623,-0.032496,-0.008276,0.044929,0.021890,...,-0.042704,-0.023139,0.047610,-0.021879,-0.048699,1,4379,1047,Empreitadas de obras públicas,43
3,-0.060817,-0.024744,0.011874,-0.039798,0.024335,0.085144,-0.014147,-0.021923,-0.032357,-0.002618,...,-0.012641,0.049787,0.032439,0.035357,0.054146,1,4706,3277,Empreitadas de obras públicas,43
4,0.001571,0.051739,0.081232,0.026330,0.015601,-0.051699,0.005150,0.051129,0.004600,0.001109,...,-0.027890,-0.072192,-0.007020,-0.032213,-0.027444,1,6862,3045,Locação de bens móveis,43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10219,-0.033006,-0.027450,-0.028070,0.017208,0.104097,0.025535,-0.012878,-0.015490,-0.044750,0.050181,...,-0.021432,0.039645,-0.024679,-0.029130,-0.002412,1,5824,4389,Aquisição de serviços,43
10220,-0.045601,0.014797,0.039917,-0.059706,0.027300,0.013217,0.006027,0.002019,-0.014111,-0.043886,...,0.022862,0.009290,0.018566,-0.009241,0.089430,2,6767,4510,Aquisição de serviços,43
10221,-0.005691,0.034652,-0.043687,-0.074397,0.079882,0.009865,0.009877,-0.013330,0.032172,0.000779,...,-0.042052,0.002473,0.037878,0.017394,-0.055897,1,4703,12,Empreitadas de obras públicas,43
10222,-0.008967,0.048813,-0.031824,-0.009013,0.119169,-0.012493,0.013489,-0.038627,-0.054581,0.013872,...,-0.033642,0.024375,0.058597,0.062644,-0.001506,3,4670,7083,Empreitadas de obras públicas,43
10223,-0.002505,0.094942,0.044165,-0.074706,0.075887,0.059517,0.007757,-0.007459,-0.097575,0.025067,...,-0.012905,0.030264,0.031896,0.048558,0.053816,2,1777,3098,Aquisição de bens móveis,43

In [1017]:
#Converting categorical data into dummy or indicator variables for Type2s
final_Type2s = pd.get_dummies(final_Type2s, prefix={'Type1Type':'Type1Type'}, 
                                              columns = ['Type1Type'],
                          drop_first=True)
final_Type2s

,col_0,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,...,contractType_Sociedade,contractType_Sociedade<br/>Aquisição de bens móveis,contractType_Sociedade<br/>Aquisição de bens móveis<br/>Aquisição de serviços,contractType_Sociedade<br/>Aquisição de bens móveis<br/>Concessão de obras públicas,contractType_Sociedade<br/>Aquisição de serviços,contractType_Sociedade<br/>Aquisição de serviços<br/>Aquisição de bens móveis,contractType_Sociedade<br/>Aquisição de serviços<br/>Locação de bens móveis,contractType_Sociedade<br/>Empreitadas de obras públicas,contractType_Sociedade<br/>Locação de bens móveis,contractType_Sociedade<br/>Locação de bens móveis<br/>Aquisição de bens móveis
0,-0.026911,-0.051014,-0.023318,-0.009499,0.060968,0.014730,-0.008912,-0.075087,0.004025,0.006439,...,0,0,0,0,0,0,0,0,0,0
1,0.084498,0.042029,0.019779,-0.020284,0.095920,-0.020238,0.067495,-0.031489,0.034687,0.034047,...,0,0,0,0,0,0,0,0,0,0
2,0.028979,0.006396,-0.018315,-0.067599,0.071495,-0.038623,-0.032496,-0.008276,0.044929,0.021890,...,0,0,0,0,0,0,0,0,0,0
3,-0.060817,-0.024744,0.011874,-0.039798,0.024335,0.085144,-0.014147,-0.021923,-0.032357,-0.002618,...,0,0,0,0,0,0,0,0,0,0
4,0.001571,0.051739,0.081232,0.026330,0.015601,-0.051699,0.005150,0.051129,0.004600,0.001109,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10219,-0.033006,-0.027450,-0.028070,0.017208,0.104097,0.025535,-0.012878,-0.015490,-0.044750,0.050181,...,0,0,0,0,0,0,0,0,0,0
10220,-0.045601,0.014797,0.039917,-0.059706,0.027300,0.013217,0.006027,0.002019,-0.014111,-0.043886,...,0,0,0,0,0,0,0,0,0,0
10221,-0.005691,0.034652,-0.043687,-0.074397,0.079882,0.009865,0.009877,-0.013330,0.032172,0.000779,...,0,0,0,0,0,0,0,0,0,0
10222,-0.008967,0.048813,-0.031824,-0.009013,0.119169,-0.012493,0.013489,-0.038627,-0.054581,0.013872,...,0,0,0,0,0,0,0,0,0,0
10223,-0.002505,0.094942,0.044165,-0.074706,0.075887,0.059517,0.007757,-0.007459,-0.097575,0.025067,...,0,0,0,0,0,0,0,0,0,0

# Build the ANNOY index using all features : Type2s

In [1018]:
#Using ANNOY: Approximate Nearest Neighbours Oh yeah! by Spotify for Type2s
from annoy import AnnoyIndex

import time
start = time.time()

f = 762


t_Type2s_all_ftrs = AnnoyIndex(f, 'angular')  #Length of item vector that will be indexed
#for index, row in dummy_df.head(1000):
   # t.add_item(index, row)
#adf = final_df.iloc[:500000, :]
for index, row in final_Type2s.iterrows():
    #print(f"index: {index}, row: {row.nif}")
    t_Type2s_all_ftrs.add_item(index, row)

t_Type2s_all_ftrs.build(10) # 10 trees
t_Type2s_all_ftrs.save('test_Type2s_all_ftrs.ann')

end = time.time()

# Total time to compute
print('\nThis function took {:.2f} s to compute.'.format(end - start))

This function took 16.48 s to compute.

# Testing with all features : Type2s

In [ ]:
#TC1
a_no = <>
a_list = [<>>]
indx = samp_Type2s.index[samp_Type2s['id'] == a_no].tolist()
print(f"Ad No.: {a_no} index: {indx}")
print("\nIndexes of Type2s to be matched: ")
print(samp_Type2s[samp_Type2s['id'].isin(a_list)]['id'])
lst = samp_Type2s[samp_Type2s['id'].isin(a_list)].index

u = AnnoyIndex(f, 'angular')
u.load('test_Type2s_all_ftrs.ann') # super fast, will just mmap the file
result = pd.DataFrame()
result['Col1'] = pd.DataFrame(u.get_nns_by_item(indx[0], 2200 )) # will find the 1000 nearest neighbors
print("\nMatch Results")
res = result[result['Col1'].isin(lst)].Col1
print(f"{len(res)} records match")
res

#Cleared Output to comply with the NDA

In [ ]:
#TC2
a_no = <>
a_list = [<>]
indx = samp_Type2s.index[samp_Type2s['id'] == a_no].tolist()
print(f"Ad No.: {a_no} index: {indx}")
print("\nIndexes of Type2s to be matched: ")
print(samp_Type2s[samp_Type2s['id'].isin(a_list)]['id'])
lst = samp_Type2s[samp_Type2s['id'].isin(a_list)].index

u = AnnoyIndex(f, 'angular')
u.load('test_Type2s_all_ftrs.ann') # super fast, will just mmap the file
result = pd.DataFrame()
result['Col1'] = pd.DataFrame(u.get_nns_by_item(indx[0], 5000 )) # will find the 1000 nearest neighbors
print("\nMatch Results")
res = result[result['Col1'].isin(lst)].Col1
print(f"{len(res)} records match")
res

#Cleared Output to comply with the NDA

# Sampling a smaller set only from the given list

In [ ]:
#using Type1 nos from the test set
ctr_list = [<>] #Info removed to comply with the NDA

#plus 10K Type1s
#samp_ctr = data_df[(data_df.ctr_Type2s == 1)].head(10000)
#samp_ctr = samp_ctr.append(data_df[data_df['id'].isin(ctr_list)]).reset_index(drop=True) 
samp_ctr_s = data_df[data_df['id'].isin(ctr_list)].reset_index(drop=True) 
samp_ctr_s 

#Cleared Output to comply with the NDA

In [1032]:
#Text Embedding for Type1 Titles

from sentence_transformers import SentenceTransformer
model = SentenceTransformer('distiluse-base-multilingual-cased-v1')

start = time.time()
embeddings_ctr_s = []

n = len(samp_ctr_s['lemm'])

print(f"There are {n} records to process today")
embeddings_ctr_s = model.encode(samp_ctr['lemm'])
print(f"{n} records are added")

end = time.time()
# Total time to compute

print('\nThis function took {:.2f} s to compute.'.format(end - start))

There are 203 records to process today
203 records are added

This function took 10.90 s to compute.

In [1033]:
ctr_embeds_df_s = pd.DataFrame(embeddings_ctr_s)
ctr_embeds_df_s.columns = ['col_'+str(num) for num in range(embeddings_ctr_s.shape[1])]
ctr_embeds_df_s

,col_0,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,...,col_502,col_503,col_504,col_505,col_506,col_507,col_508,col_509,col_510,col_511
0,-0.012597,-0.021169,0.004364,-0.034760,0.011707,-0.031097,-0.009160,0.011405,0.027637,-0.011639,...,0.015424,0.001912,0.017126,-0.045687,0.080389,-0.012189,0.080207,-0.003466,-0.027553,0.053678
1,0.058579,0.001575,-0.023590,-0.004432,0.068550,0.020469,-0.021316,0.035644,0.040441,0.011761,...,0.021265,-0.053317,-0.028228,-0.050260,0.036425,-0.063614,0.001759,-0.003221,-0.011604,0.059579
2,-0.039020,-0.079821,-0.015701,-0.017194,0.064387,-0.022447,0.009039,0.041438,0.020767,-0.007066,...,-0.011862,0.010413,0.044966,-0.001938,0.058422,0.008124,0.054385,0.036261,0.031451,0.026654
3,0.059088,0.050582,0.032243,-0.064278,0.104531,-0.102314,0.021116,0.002731,-0.096195,0.028712,...,0.033884,-0.052595,0.076570,-0.007741,-0.008991,-0.060037,-0.008681,0.022304,-0.025945,-0.045215
4,0.053640,0.086881,-0.069122,0.024354,-0.068090,0.072996,0.007695,0.011354,0.017544,0.006993,...,0.018511,-0.031353,0.002072,0.021107,-0.004926,0.006753,-0.008968,-0.036318,-0.004508,0.010584
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198,-0.019831,0.004905,0.027139,-0.016492,-0.058190,0.028122,-0.017875,0.019658,-0.020580,-0.023857,...,-0.003145,-0.041780,-0.004194,0.009265,-0.030309,0.020869,0.053502,0.048767,-0.002036,-0.012913
199,-0.025081,-0.052650,-0.045189,-0.000725,-0.001611,0.042363,-0.022679,0.031628,0.016473,-0.020218,...,0.035204,-0.007561,0.009151,-0.000184,-0.002363,0.003779,-0.002796,0.112329,0.023464,-0.030824
200,0.007497,0.047767,-0.001658,-0.026412,0.055747,-0.010143,0.070942,0.019195,-0.034207,0.040163,...,0.031154,0.001890,0.012175,0.001437,0.017530,0.021713,0.050491,-0.057415,-0.008700,-0.009758
201,0.007973,-0.006567,0.007972,-0.024185,0.037945,-0.024951,0.021616,0.010492,-0.025213,0.039273,...,0.042061,-0.075808,-0.054949,0.004109,0.009871,0.007268,0.058270,0.018326,0.012770,0.049915
202,0.006300,-0.034266,-0.021577,-0.033345,0.005970,0.015349,-0.009623,-0.016358,-0.022686,0.004165,...,0.060385,-0.022496,-0.006637,-0.033977,0.061615,0.003057,0.069206,-0.045256,0.009401,0.048284

In [1034]:
#Replacing text with the embeddings for Type1s : multilingual
final_ctr_s = pd.concat([ctr_embeds_df_s * 0.9, samp_ctr['parsedPriceBracket'] * 0.1, samp_ctr['category1sSplit'] * 0, samp_ctr['nif'] * 0], axis=1)
#final_ctr = final_ctr.drop(columns = ['lemm'])
final_ctr_s

,col_0,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,...,col_505,col_506,col_507,col_508,col_509,col_510,col_511,parsedPriceBracket,cpvsSplit,nif
0,-0.011337,-0.019052,0.003927,-0.031284,0.010536,-0.027988,-0.008244,0.010264,0.024874,-0.010475,...,-0.041119,0.072350,-0.010970,0.072187,-0.003120,-0.024798,0.048310,0.1,0,0
1,0.052721,0.001417,-0.021231,-0.003988,0.061695,0.018422,-0.019184,0.032079,0.036397,0.010585,...,-0.045234,0.032783,-0.057253,0.001583,-0.002899,-0.010444,0.053621,0.1,0,0
2,-0.035118,-0.071839,-0.014131,-0.015474,0.057949,-0.020202,0.008135,0.037294,0.018690,-0.006359,...,-0.001745,0.052580,0.007311,0.048947,0.032635,0.028306,0.023988,0.1,0,0
3,0.053179,0.045524,0.029019,-0.057850,0.094078,-0.092082,0.019005,0.002458,-0.086575,0.025841,...,-0.006967,-0.008092,-0.054033,-0.007813,0.020074,-0.023350,-0.040694,0.1,0,0
4,0.048276,0.078193,-0.062210,0.021919,-0.061281,0.065697,0.006926,0.010218,0.015790,0.006293,...,0.018997,-0.004433,0.006077,-0.008072,-0.032686,-0.004057,0.009525,0.1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198,-0.017847,0.004415,0.024425,-0.014843,-0.052371,0.025310,-0.016088,0.017692,-0.018522,-0.021471,...,0.008338,-0.027278,0.018783,0.048152,0.043890,-0.001833,-0.011621,0.1,0,0
199,-0.022573,-0.047385,-0.040670,-0.000652,-0.001450,0.038126,-0.020411,0.028465,0.014826,-0.018196,...,-0.000166,-0.002127,0.003401,-0.002516,0.101096,0.021118,-0.027741,0.1,0,0
200,0.006748,0.042990,-0.001492,-0.023771,0.050172,-0.009129,0.063847,0.017276,-0.030787,0.036147,...,0.001293,0.015777,0.019542,0.045442,-0.051673,-0.007830,-0.008782,0.1,0,0
201,0.007176,-0.005910,0.007175,-0.021767,0.034151,-0.022456,0.019454,0.009442,-0.022692,0.035346,...,0.003698,0.008884,0.006541,0.052443,0.016494,0.011493,0.044924,0.1,0,0
202,0.005670,-0.030839,-0.019419,-0.030010,0.005373,0.013814,-0.008660,-0.014722,-0.020418,0.003749,...,-0.030580,0.055454,0.002751,0.062285,-0.040730,0.008461,0.043456,0.2,0,0

In [1035]:
#Using ANNOY: Approximate Nearest Neighbours Oh yeah! by Spotify for Type1s
from annoy import AnnoyIndex

import time
start = time.time()

f = 515

t_ctr_ftr_s = AnnoyIndex(f, 'angular')  #Length of item vector that will be indexed
#for index, row in dummy_df.head(1000):
   # t.add_item(index, row)
#adf = final_df.iloc[:500000, :]
for index, row in final_ctr_s.iterrows():
    #print(f"index: {index}, row: {row.nif}")
    t_ctr_ftr_s.add_item(index, row)

t_ctr_ftr_s.build(10) # 10 trees
t_ctr_ftr_s.save('test_ctr_ftr_s.ann')

end = time.time()

# Total time to compute
print('\nThis function took {:.2f} s to compute.'.format(end - start))

This function took 0.23 s to compute.

In [ ]:
#TC1
c_no = <>
c_list = [<>]


indx = samp_ctr.index[samp_ctr['id'] == c_no].tolist()
print(f"Type1 No.: {c_no} index: {indx}")
print("\nIndexes of Type1s to be matched: ")
print(samp_ctr[samp_ctr['id'].isin(c_list)]['id'])
lst = samp_ctr[samp_ctr['id'].isin(c_list)].index

u = AnnoyIndex(f, 'angular')
u.load('test_ctr_ftr_s.ann') # super fast, will just mmap the file
result = pd.DataFrame()
result['Col1'] = pd.DataFrame(u.get_nns_by_item(indx[0], 36 )) # will find the 1000 nearest neighbors
print("\nMatch Results")
res = result[result['Col1'].isin(lst)].Col1
print(f"{len(res)} records match")
res

#Cleared Output to comply with the NDA

In [ ]:
#TC1
#To view the full list of result
u = AnnoyIndex(f, 'angular')
u.load('test_ctr_ftr_s.ann') # super fast, will just mmap the file
result = pd.DataFrame()
result = u.get_nns_by_item(<>, 10 ) # will find the 1000 nearest neighbors

#result.sort()
print(result)

#Cleared Output to comply with the NDA

In [ ]:
#TC1
samp_ctr[['id', 'objectBriefDescription', 'lemm', 'category1sSplit', 'nif', 'parsedPriceBracket']][samp_ctr.index.isin([168, 164, 37, 67, 165, 52, 65, 66, 76, 196])]

In [ ]:
#TC2
c_no = <>
c_list = [<>]


indx = samp_ctr.index[samp_ctr['id'] == c_no].tolist()
print(f"Type1 No.: {c_no} index: {indx}")
print("\nIndexes of Type1s to be matched: ")
print(samp_ctr[samp_ctr['id'].isin(c_list)]['id'])
lst = samp_ctr[samp_ctr['id'].isin(c_list)].index

u = AnnoyIndex(f, 'angular')
u.load('test_ctr_ftr_s.ann') # super fast, will just mmap the file
result = pd.DataFrame()
result['Col1'] = pd.DataFrame(u.get_nns_by_item(indx[0], 10 )) # will find the 1000 nearest neighbors
print("\nMatch Results")
res = result[result['Col1'].isin(lst)].Col1
print(f"{len(res)} records match")
res

#Cleared Output to comply with the NDA

In [ ]:
#TC2
#To view the full list of result
u = AnnoyIndex(f, 'angular')
u.load('test_ctr_ftr_s.ann') # super fast, will just mmap the file
result = pd.DataFrame()
result = u.get_nns_by_item(<>, 10 ) # will find the 1000 nearest neighbors

#result.sort()
print(result)

#Cleared Output to comply with the NDA

In [ ]:
#TC2
samp_ctr[['id', 'objectBriefDescription', 'lemm', 'category1sSplit', 'nif', 'parsedPriceBracket']][samp_ctr.index.isin([182, 53, 29, 46, 70, 189, 150, 92, 48, 137])]

In [296]:
import pandas as pd

#Load the data for testing
samp_ctr = pd.read_csv('./samp_ctr.csv',lineterminator='\n', index_col=0)  
samp_Type2s = pd.read_csv('./samp_Type2s.csv',lineterminator='\n', index_col=0)

# Extra Test Cases: Type1s

In [ ]:
#
c_no = <>
c_list = [<>>]


indx = samp_ctr.index[samp_ctr['id'] == c_no].tolist()
print(f"Type1 No.: {c_no} index: {indx}")
print("\nIndexes of Type1s to be matched: ")
print(samp_ctr[samp_ctr['id'].isin(c_list)]['id'])
lst = samp_ctr[samp_ctr['id'].isin(c_list)].index

u = AnnoyIndex(f, 'angular')
u.load('test_ctr_ftr_2_wt.ann') # super fast, will just mmap the file
result = pd.DataFrame()
result['Col1'] = pd.DataFrame(u.get_nns_by_item(indx[0], 863 )) # will find the 1000 nearest neighbors
print("\nMatch Results")
res = result[result['Col1'].isin(lst)].Col1
print(f"{len(res)} records match")
res

#Cleared Output to comply with the NDA

In [ ]:
#To view the full list of result
u = AnnoyIndex(f, 'angular')
u.load('test_ctr_ftr_2_wt.ann') # super fast, will just mmap the file
result = pd.DataFrame()
result = u.get_nns_by_item(<>, 10 ) # will find the 1000 nearest neighbors

#result.sort()
print(result)

#Cleared Output to comply with the NDA

In [ ]:
#TC1
samp_ctr[['id', 'objectBriefDescription', 'lemm', 'category1sSplit','category1s_text', 'nif', 'parsedPriceBracket']][samp_ctr.index.isin([10106, 2964, 386, 4725, 9963, 2841, 405, 1266, 10159, 5890])]

In [610]:
final_ctr.iloc[7479]

ctr_ads                                                                                 1.0
id                                                                                4990474.0
country                                                                                49.0
parsedPriceBracket                                                                      1.0
executionDeadlineDays                                                                  11.0
                                                                                    ...
contractType_Sociedade<br/>Aquisição de serviços<br/>Aquisição de bens móveis           0.0
contractType_Sociedade<br/>Aquisição de serviços<br/>Locação de bens móveis             0.0
contractType_Sociedade<br/>Empreitadas de obras públicas                                0.0
contractType_Sociedade<br/>Locação de bens móveis                                       0.0
contractType_Sociedade<br/>Locação de bens móveis<br/>Aquisição de bens móveis          0.0
Name: 7479, Length: 781, dtype: float64

In [ ]:
#TC1
c_no = <>
c_list = [<>]

indx = samp_ctr.index[samp_ctr['id'] == c_no].tolist()
print(f"Type1 No.: {c_no} index: {indx}")
print("\nIndexes of Type1s to be matched: ")
print(samp_ctr[samp_ctr['id'].isin(c_list)]['id'])
lst = samp_ctr[samp_ctr['id'].isin(c_list)].index

u = AnnoyIndex(f, 'angular')
u.load('test_ctr_ftr_2_wt.ann') # super fast, will just mmap the file
result = pd.DataFrame()
result['Col1'] = pd.DataFrame(u.get_nns_by_item(indx[0], 3000 )) # will find the 1000 nearest neighbors
print("\nMatch Results")
res = result[result['Col1'].isin(lst)].Col1
print(f"{len(res)} records match")
res

#Cleared Output to comply with the NDA

In [ ]:
#To view the full list of result
u = AnnoyIndex(f, 'angular')
u.load('test_ctr_ftr_2_wt.ann') # super fast, will just mmap the file
result = pd.DataFrame()
result = u.get_nns_by_item(<>, 10 ) # will find the 1000 nearest neighbors

#result.sort()
print(result)

#Cleared Output to comply with the NDA

In [ ]:
#TC1
samp_ctr[['id', 'objectBriefDescription', 'lemm', 'category1sSplit','category1s_text', 'nif', 'parsedPriceBracket']][samp_ctr.index.isin([10133, 10041, 8071, 617, 10161, 10130, 9999, 10079, 688, 682])]

In [ ]:
#TC2
c_no = <>
c_list = [<>]

indx = samp_ctr.index[samp_ctr['id'] == c_no].tolist()
print(f"Type1 No.: {c_no} index: {indx}")
print("\nIndexes of Type1s to be matched: ")
print(samp_ctr[samp_ctr['id'].isin(c_list)]['id'])
lst = samp_ctr[samp_ctr['id'].isin(c_list)].index

u = AnnoyIndex(f, 'angular')
u.load('test_ctr_ftr_2_wt.ann') # super fast, will just mmap the file
result = pd.DataFrame()
result['Col1'] = pd.DataFrame(u.get_nns_by_item(indx[0], 500 )) # will find the 1000 nearest neighbors
print("\nMatch Results")
res = result[result['Col1'].isin(lst)].Col1
print(f"{len(res)} records match")
res

#Cleared Output to comply with the NDA

In [ ]:
#To view the full list of result
u = AnnoyIndex(f, 'angular')
u.load('test_ctr_ftr_2_wt.ann') # super fast, will just mmap the file
result = pd.DataFrame()
result = u.get_nns_by_item(<>, 10 ) # will find the 1000 nearest neighbors

#result.sort()
print(result)

#Cleared Output to comply with the NDA

In [ ]:
#TC1
samp_ctr[['id', 'objectBriefDescription', 'lemm', 'category1sSplit','category1s_text', 'nif', 'parsedPriceBracket']][samp_ctr.index.isin([10089, 10059, 10062, 10157, 1465, 3572, 750, 975, 10089, 2870, 563, 10071, 1285])]

In [ ]:
#TC3
c_no = <>
c_list = [<>]

indx = samp_ctr.index[samp_ctr['id'] == c_no].tolist()
print(f"Type1 No.: {c_no} index: {indx}")
print("\nIndexes of Type1s to be matched: ")
print(samp_ctr[samp_ctr['id'].isin(c_list)]['id'])
lst = samp_ctr[samp_ctr['id'].isin(c_list)].index

u = AnnoyIndex(f, 'angular')
u.load('test_ctr_ftr_2_wt.ann') # super fast, will just mmap the file
result = pd.DataFrame()
result['Col1'] = pd.DataFrame(u.get_nns_by_item(indx[0], 500 )) # will find the 1000 nearest neighbors
print("\nMatch Results")
res = result[result['Col1'].isin(lst)].Col1
print(f"{len(res)} records match")
res

#Cleared Output to comply with the NDA

In [ ]:
#To view the full list of result
u = AnnoyIndex(f, 'angular')
u.load('test_ctr_ftr_2_wt.ann') # super fast, will just mmap the file
result = pd.DataFrame()
result = u.get_nns_by_item(<>, 10 ) # will find the 1000 nearest neighbors

#result.sort()
print(result)

#Cleared Output to comply with the NDA

In [ ]:
#TC3
samp_ctr[['id', 'objectBriefDescription', 'lemm', 'category1sSplit','category1s_text', 'nif', 'parsedPriceBracket']][samp_ctr.index.isin([10147, 8928, 9782, 7516, 5880, 7543, 5895, 1340, 8392, 7510])]

In [ ]:
#TC4
c_no = <>
c_list = [<>]

indx = samp_ctr.index[samp_ctr['id'] == c_no].tolist()
print(f"Type1 No.: {c_no} index: {indx}")
print("\nIndexes of Type1s to be matched: ")
print(samp_ctr[samp_ctr['id'].isin(c_list)]['id'])
lst = samp_ctr[samp_ctr['id'].isin(c_list)].index

u = AnnoyIndex(f, 'angular')
u.load('test_ctr_ftr_2_wt.ann') # super fast, will just mmap the file
result = pd.DataFrame()
result['Col1'] = pd.DataFrame(u.get_nns_by_item(indx[0], 3000 )) # will find the 1000 nearest neighbors
print("\nMatch Results")
res = result[result['Col1'].isin(lst)].Col1
print(f"{len(res)} records match")
res

#Cleared Output to comply with the NDA

In [ ]:
#To view the full list of result
u = AnnoyIndex(f, 'angular')
u.load('test_ctr_ftr_2_wt.ann') # super fast, will just mmap the file
result = pd.DataFrame()
result = u.get_nns_by_item(<>, 10 ) # will find the 1000 nearest neighbors

#result.sort()
print(result)

#Cleared Output to comply with the NDA

In [ ]:
final_ctr

In [ ]:
#To view the full list of result
u = AnnoyIndex(f, 'angular')
u.load('test.ann') # super fast, will just mmap the file
result = pd.DataFrame()
result = u.get_nns_by_item(<>, 500 ) # will find the 1000 nearest neighbors

#result.sort()
print(result)

#Cleared Output to comply with the NDA

# Extra Test Cases : Type2s

In [ ]:
#TC1
a_no = <>
a_list = [<>]
indx = final_Type2s.index[final_Type2s['id'] == a_no].tolist()
print(f"Ad No.: {a_no} index: {indx}")
print("\nIndexes of Type2s to be matched: ")
print(final_Type2s[final_Type2s['id'].isin(a_list)]['id'])
lst = final_Type2s[final_Type2s['id'].isin(a_list)].index

u = AnnoyIndex(f, 'angular')
u.load('test_Type2s.ann') # super fast, will just mmap the file
result = pd.DataFrame()
result['Col1'] = pd.DataFrame(u.get_nns_by_item(indx[0], 500 )) # will find the 1000 nearest neighbors
print("\nMatch Results")
res = result[result['Col1'].isin(lst)].Col1
print(f"{len(res)} records match")
res

#Cleared Output to comply with the NDA

In [ ]:
#To view the full list of result
u = AnnoyIndex(f, 'angular')
u.load('test_Type2s.ann') # super fast, will just mmap the file
result = pd.DataFrame()
result = u.get_nns_by_item(<>, 10 ) # will find the 1000 nearest neighbors

result.sort()
print(result)

In [ ]:
#To view the full list of result
c_no_list = [<>]

u = AnnoyIndex(f, 'angular')
u.load('test_ctr_ftr_2_wt.ann') # super fast, will just mmap the file
build_csv_df = pd.DataFrame()

for c_no in c_no_list:
    result_df  = pd.DataFrame()
    indx = samp_ctr.index[samp_ctr['id'] == c_no].to_list()
    result_df = pd.DataFrame(u.get_nns_by_item(indx[0], 10 )) # will find the 10 nearest neighbors
    result_df['rank']= result_df.index+1
    result_df['ref_Type1_no'] = c_no
    result_df.rename(columns = {0:'index'}, inplace = True)

    abc = samp_ctr[samp_ctr.index.isin(result_df['index'])]
    abc['index']= abc.index
    result_df = result_df.merge(abc, how='inner',on='index')
    build_csv_df = build_csv_df.append(result_df)
    
print(build_csv_df)
build_csv_df.to_csv("./top_10_matches_Type1s.csv")

#Cleared Output to comply with the NDA

# Trying FAISS

In [1061]:
#pip install faiss-cpu

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Collecting faiss-cpu
  Downloading faiss_cpu-1.7.3-cp38-cp38-macosx_10_9_x86_64.whl (5.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 1.6 MB/s eta 0:00:0000:0100:01
Installing collected packages: faiss-cpu
Successfully installed faiss-cpu-1.7.3
Note: you may need to restart the kernel to use updated packages.

In [72]:
ctr_embeds_df_2

,col_0,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,...,col_502,col_503,col_504,col_505,col_506,col_507,col_508,col_509,col_510,col_511
0,-0.008769,-0.035696,-0.081959,-0.065422,0.106423,-0.006806,0.014415,-0.019768,-0.007022,0.022455,...,-0.053410,-0.004052,0.065656,-0.080810,0.016209,-0.011536,0.013828,0.040486,0.051302,0.014021
1,0.041093,-0.032101,-0.062681,-0.027410,0.083845,-0.030770,-0.019008,-0.087988,0.053893,0.023575,...,-0.024192,-0.008800,0.037727,-0.035784,0.050928,-0.014732,-0.041200,0.017684,-0.089092,0.001281
2,0.026384,-0.036660,0.010439,0.003870,-0.000859,0.011253,-0.004238,-0.006598,-0.041758,-0.015051,...,0.031650,-0.013433,-0.012822,-0.015036,-0.095395,-0.002170,-0.000507,-0.061892,0.020786,-0.019073
3,0.013121,-0.041674,-0.012382,-0.035365,0.101415,0.027916,0.009208,-0.016659,0.002207,0.010975,...,0.018381,-0.024724,-0.014496,-0.037792,0.022144,-0.045335,-0.020217,-0.001707,0.073547,0.006090
4,0.006715,-0.055337,0.003673,-0.004573,0.057083,0.051284,0.037291,-0.038526,-0.037250,0.031229,...,0.064072,0.038382,-0.078159,0.047688,0.032358,0.024627,-0.033376,0.013414,-0.022359,0.049040
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10198,-0.019831,0.004905,0.027139,-0.016492,-0.058190,0.028122,-0.017875,0.019658,-0.020580,-0.023857,...,-0.003145,-0.041780,-0.004194,0.009265,-0.030309,0.020870,0.053502,0.048767,-0.002036,-0.012913
10199,-0.025081,-0.052650,-0.045189,-0.000725,-0.001611,0.042363,-0.022679,0.031628,0.016473,-0.020218,...,0.035204,-0.007561,0.009151,-0.000184,-0.002363,0.003779,-0.002796,0.112329,0.023464,-0.030824
10200,0.007497,0.047767,-0.001658,-0.026412,0.055747,-0.010143,0.070942,0.019195,-0.034207,0.040163,...,0.031154,0.001890,0.012175,0.001437,0.017530,0.021713,0.050491,-0.057415,-0.008700,-0.009758
10201,0.007973,-0.006567,0.007972,-0.024185,0.037945,-0.024951,0.021616,0.010492,-0.025213,0.039273,...,0.042061,-0.075808,-0.054949,0.004109,0.009871,0.007268,0.058270,0.018326,0.012770,0.049915
10202,0.006300,-0.034266,-0.021577,-0.033345,0.005970,0.015349,-0.009623,-0.016358,-0.022686,0.004165,...,0.060385,-0.022496,-0.006637,-0.033977,0.061615,0.003057,0.069206,-0.045256,0.009401,0.048284

In [ ]:
import faiss 

start = time.time()

vectors = embeddings_ctr_2
vec_dim = vectors.shape[1]

index = faiss.IndexFlatL2(vec_dim)
faiss.normalize_L2(vectors)
index.add(vectors)

end = time.time()
# Total time to compute

print('\nThis function took {:.2f} s to compute.'.format(end - start))

# FAISS ran too slow - it killed my kernel twice 
# Readings off the internet suggest that supporting M1 GPU is neither currently supported nor 
# planned  and need to add a lot of implementations even if M1 GPU would be supported, because faiss uses CUDA 
# to implement GPGPU codes and CUDA can't work on M1 GPU.